### ISSUE TITLE
ValueError: object arrays are not supported

### ISSUE THREAD

**Issue by ankurkumar897614** [dcajasn/Riskfolio-Lib#100]
First of all thanks for the wonderful stuff. Really amazing to see the functionality of  this library.

My issue - My all columns are in float 64 data types but still I am getting this issue. I have also installed all dependencies correctly, running Python 3.9.

Please suggest

**Comment by dcajasn** [comment]
Hi @ankurkumar897614 

It is a problem with your data, please revise carefully your data before rise an issue. This is not a Riskfolio-Lib issue.

Best,
Dany

**Comment by ankurkumar897614** [comment]
Dear Deny,

Thanks a ton for your prompt response and deep apologies if I hurt you by
mistake due to my limited knowledge/ understanding.

I am running absolutely the same code which you have mentioned in the
example (downloaded data for same tickers and for same time period). So I
think data is not a problem from my side but may be some other technical
glitch from my side only. I have attached my notebook for your kind
perusal.

I have checked that all dependencies are also up to date.

Just seeking your guidance. You have developed an amazing piece of work
hence i think it should get popularized. Generally I do asset allocation
either through DeepPortfolio (using Autoencoder) or using some linear ways
by combining DBScan clustering, coefficient of variance and PCA with t-SNE.

Your approach involves more domain knowledge hence I think I should make it
popular within my Quants communities.

Once again sorry if I raised the issue by mistake.

Many thanks in advance for your anticipated support.

Regards
Ankur Sharma

**Comment by dcajasn** [comment]
Hi @ankurkumar897614,

I didn't see a notebook attached or a screenshot that shows the problem but for my experience "ValueError: object arrays are not supported" happens when people don't check their dataframe and try to pass a dataframe that has strings, np.nan or np.inf values instead of float values to Riskfolio-Lib.

Best,
Dany
