### ISSUE TITLE
ENH: plotly as well as matplotlib for network graphs

### ISSUE THREAD

**Issue by rraymondgh** [dcajasn/Riskfolio-Lib#101]
See https://stackoverflow.com/questions/73625534/transfer-custom-plotfunction-to-plotly

Effectively have short cutted `PlotFunctions.plot_network()` stripping out **matplotlib** to return `pos` and `G`.  Then have created new function that can generate a **plotly** figure from the **networkx** constructs.

Happy to generate a PR to provide this functionality if you feel this is a valid enhancement to **riskfolio**

**Comment by dcajasn** [comment]
Hi @rraymondgh,

I don't plan to  include plotly charts in riskfolio-lib. I like the way Plotly charts looks, but Plotly library changes too much and this makes it difficult to maintain features that use Plotly objects.

Best,
Dany
