### ISSUE TITLE
`plot_frontier`: ill-formed precondition on weights

### ISSUE THREAD

**Issue by Alexander-Shukaev** [dcajasn/Riskfolio-Lib#103]
https://github.com/dcajasn/Riskfolio-Lib/blob/af55dc242baf8e294c66f6ff662b175ce2227922/riskfolio/PlotFunctions.py#L355

The above precondition appears to be ill-formed as per implementation below:

https://github.com/dcajasn/Riskfolio-Lib/blob/af55dc242baf8e294c66f6ff662b175ce2227922/riskfolio/PlotFunctions.py#L429

Essentially, I was expecting that passing a matrix of weights would scatter each corresponding portfolio (per column) on a plot, not just one as enforced now.

**Comment by dcajasn** [comment]
Hi @Alexander-Shukaev,

You are right, I've just fixed.

Best,
Dany
