### ISSUE TITLE
HRP Constraints file columns error

### ISSUE THREAD

**Issue by ultra1971** [dcajasn/Riskfolio-Lib#108]
When run a HRP optimization with constriants
  File "/home/algotrading/anaconda3/lib/python3.8/site-packages/riskfolio/ConstraintsFunctions.py", line 905, in hrp_constraints
    raise ValueError("constraints must have ten columns")

ValueError: constraints must have ten columns

But reviewing line 905, I understand that the condition need to be corrected.

    if constraints.shape[1] != 6:
        raise ValueError("constraints must have ten columns")

**Comment by dcajasn** [comment]
Hi @ultra1971,

I'm going to fix that mistake. Thanks.

Best,
Dany

**Comment by ultra1971** [comment]
Gracias, Dany !
Mariano V.
