### ISSUE TITLE
Rebalancing frequency

### ISSUE THREAD

**Issue by teracapital** [dcajasn/Riskfolio-Lib#113]
Hi quick doubt, when you pass the assets returns and weights to rislfolio (like in rp.plot_tabel) what rp consider to perform the calculations, fixed initial weights with no rebalance (weights varying from assets prices movement), or fixed weights during the entire period (daily rebalancing).

**Comment by dcajasn** [comment]
Hi @teracapital,

This is not an issue. Please read the source code.

Best,
Dany
