### ISSUE TITLE
Problem with Tutorial 18

### ISSUE THREAD

**Issue by po1ar** [dcajasn/Riskfolio-Lib#115]
Hi, recently I've been trying to recreate Tutorial 18 but when I run the 3.1 cell, I keep getting this error. Any ideas on how to fix?
<img width="1449" alt="Screen Shot 2022-10-20 at 6 14 06 PM" src="https://user-images.githubusercontent.com/59060841/197069179-a9be4448-08f0-4979-b034-dd786023e64b.png">

**Comment by dcajasn** [comment]
Hi @po1ar,

It's a problem with the data, check if all tickers are available on yfinance.

Best,
Dany

**Comment by po1ar** [comment]
@dcajasn hey, checked all the tickers, and they're all available on yfinance.

**Comment by dcajasn** [comment]
I think it's a problem with vectorbt, I used version 0.23 to build that tutorial, so there is no guarantee that works with new versions.

**Comment by po1ar** [comment]
I installed version 0.23 and I'm getting the same error.

**Comment by replacementAI** [comment]
Can confirm this doesnt work with 0.22 or the latest version either. @po1ar were you able to find a work around?

**Comment by po1ar** [comment]
@replacementAI nah, I kinda moved on passed it. Was looking to have this as a weekend project but I couldn't get it to work :(

**Comment by replacementAI** [comment]
@dcajasn any way we can help debugging the issue?

**Comment by replacementAI** [comment]
Any update @dcajasn ?

**Comment by dcajasn** [comment]
No because it's a problem with vectorbt, in my computer it runs fine. Since vectorbt pro was released, some users told me that there were problems installing vectorbt.

**Comment by replacementAI** [comment]
@dcajasn https://github.com/polakowo/vectorbt/discussions/536

**Comment by replacementAI** [comment]
@po1ar The issue seems to be that MOSEK is a commercial solver that needs to be set up before hand

**Comment by replacementAI** [comment]
@dcajasn is there a list of solvers available in the documentation?

**Comment by dcajasn** [comment]
Hi, documentation specify that for some examples need mosek solver with an academic or free license.

**Comment by replacementAI** [comment]
> Hi, documentation specify that for some examples need mosek solver with an academic or free license.

This can be closed then. On an unrelated note, could you create an example on performance of different risk measures with HERC? Thanks for your work!
