### ISSUE TITLE
Linear Constraints Doesn't work on HRP Optimization

### ISSUE THREAD

**Issue by dontwastetime** [dcajasn/Riskfolio-Lib#118]
Hi,
It seems that HRP does not support constraints on the max total weights in a particular class (e.g. industry, sector, etc)? I tried "Classes" in the constraints functions, seems like it doesn't work. I wonder how to make group constraints work? E.g. asset a +asset b + asset c <=0.5

Thanks!

**Comment by dcajasn** [comment]
Hi @dontwastetime,

If you read documentation, hierarchical clustering portfolios don't support linear constraints.

Best,
Dany

**Comment by dontwastetime** [comment]
Hi @dcajasn 

Do you mean HRP doesn't support linear constraints or the package doesn't support? Thank you!

**Comment by dcajasn** [comment]
HRP doesn't support linear constraints.

**Comment by dontwastetime** [comment]
Hi @dcajasn 

From the paper you referred in tutorial 29: " Johann Pfitzinger & Nico Katzke (2019).", it shows that HRP is able to add group constraints in the recursive bisection step. So I guess HRP does support linear constraints? Looking forward to hearing your opinion. Thanks!

**Comment by dcajasn** [comment]
Hi @dontwastetime,

I read the paper, also I read the repository https://github.com/jpfitzinger/ClusterPortfolios, and the constraints are not linear, only based on upper and lower bounds on each asset in groups.
