### ISSUE TITLE
 module 'riskfolio' has no attribute 'Portfolio'

### ISSUE THREAD

**Issue by GiulioTrigila** [dcajasn/Riskfolio-Lib#119]
Any help is appreciated! 
I have installed riskfolio today via pip install. When I run:

import riskfolio as rp
port = rp.Portfolio(returns=Y)

(Where Y has been defined following the example in https://nbviewer.org/github/dcajasn/Riskfolio-Lib/blob/master/examples/Tutorial%201.ipynb)

I get the error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-583d31f55d26> in <module>
      2 
      3 # Building the portfolio object
----> 4 port = rp.Portfolio(returns=Y)
      5 
      6 # Calculating optimal portfolio

AttributeError: module 'riskfolio' has no attribute 'Portfolio'

It seems to me that riskfolio is installed correctly and that it is looking at the right folder where riskfolio is installed:
~/.local/lib/python3.6/site-packages/riskfolio$ 

The command  
rp.\__path\__   returns 

[~/.local/lib/python3.6/site-packages/riskfolio']

when from shell I type  ls ~/.local/lib/python3.6/site-packages/riskfolio I get 

AuxFunctions.py          ParamsEstimation.py  Prueba.py
ConstraintsFunctions.py  PlotFunctions.py     __pycache__
__init__.py              Portfolio.py         RiskFunctions.py

Thanks!

**Comment by dcajasn** [comment]
Hi @GiulioTrigila,

Just uninstall and reinstall.

Best,
Dany
