### ISSUE TITLE
Tutorial 2

### ISSUE THREAD

**Issue by plajos1** [dcajasn/Riskfolio-Lib#121]
In this tutorial the factors and the assets are added together before donloading the data. This causes a size problem when estimating the Mean Variance Portfolios.

To overcome this I have adjusted the size of X with the following code:

X = data[factors].pct_change().dropna()
Y = data[assets].pct_change().dropna()

display(X.head())
meret = Y.values.shape[0]
X = X[-meret:]

**Comment by dcajasn** [comment]
Hi @plajos1 

The error is fixed in version 4.0.2.

Best,
Dany
