### ISSUE TITLE
NCO - 'Portfolio' has no attribute 'Portfolio'

### ISSUE THREAD

**Issue by enexqnt** [dcajasn/Riskfolio-Lib#128]
After updating the library to the latest version, when I try to optimise with NCO I get this error:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/100087445/206863620-7747f09d-733a-468f-b138-7ae745f3d0a2.png">

I would like to take this opportunity to congratulate Dany Cajas for this awesome library!

**Comment by dcajasn** [comment]
It's strange that this is happen, try to uninstall and reinstall the library. Maybe when I was modifying the code to make the documentation works on readthedocs, I moved something 😅

**Comment by dcajasn** [comment]
Hi Giulio, 

I've just fixed the error in version 4.0.3. Thanks for notifying me of the error. On the other hand, I really like the notebooks you share on LinkedIn, are very impressive.

Best,
Dany

**Comment by enexqnt** [comment]
Now it works, thanks again for the work you are doing
