### ISSUE TITLE
You must convert self.cov to a positive definite matrix

### ISSUE THREAD

**Issue by duke2048** [dcajasn/Riskfolio-Lib#129]
Hi

I'm using 

`port = rp.HCPortfolio(returns=returns)`

and I'm getting this message: _You must convert self.cov to a positive definite matrix_

Is there an example how to fix the covariance matrix?

**Comment by dcajasn** [comment]
Hi @duke2048 

If it works, there is no problem. However, the message appears when some eigenvalues are positive but below a threshold. 

Best,
Dany
