### ISSUE TITLE
Margin Per Asset Constraint

### ISSUE THREAD

**Issue by AnkitAggarwalAlphagrep** [dcajasn/Riskfolio-Lib#130]
Hi

This lib is awesome. Thanks for creating it

I'm trying to solve the below problem.

We define a budget for our long short allocation (Sum(W) == 0). Suppose one of the asset in that portfolio get weight of 25% and this means if we are allocating the 10 million then that asset will get 1 Mil but out margin constraints should limit this position to 500k USD. Now if I add a constraint that w[Asset] < 500k USD/ 10 Million. This can assign the weight of Asset as 0.25% but this won't utilize the complete margin. Now to solve this we normalize this weights as W[Assset] / Sum(abs(w)). But this will again break the 500k Usd constraint?
Is there any way to solve above?

Thanks,
Ankit

**Comment by dcajasn** [comment]
Hi @AnkitAggarwalAlphagrep,

This is not an issue.

Best,
Dany
