### ISSUE TITLE
Install problem with 4.0.x versions

### ISSUE THREAD

**Issue by plajos1** [dcajasn/Riskfolio-Lib#136]
I was happy to see the new versions, but un fortunatley I was not able to install any of them. I have three confings: W8.1, W10, ubuntu. I am using PyCharm, but I have tried to install directly with pip. None of them worked. Here is a detailed error note from W8.1 PyCharm:

Collecting Riskfolio-Lib==4.0.3
  Using cached Riskfolio-Lib-4.0.3.tar.gz (12.9 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\Louis\AppData\Local\Temp\pip-install-u0z7wn8g\riskfolio-lib_717f395aa901483bbb9e438b122fa86e\setup.py", line 6, in <module>
      from pybind11.setup_helpers import Pybind11Extension, build_ext
  ModuleNotFoundError: No module named 'pybind11'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by dcajasn** [comment]
Hi @plajos1 

The error said "ModuleNotFoundError: No module named 'pybind11'", so just install pybind11 using pip install pybind11.

Best
Dany

**Comment by plajos1** [comment]
Unfortunately error messages not always telling the real reason of a problem: running the pybind install tells that the requirement is already satisfied version 2.10.1. for my system. To make sure that nothing affects the installation I've tried an installation onto a virtual environment and true, there was no pybind11 in that one. Installing pybind11 into the venv the error message is the same as for all other configs:

Collecting Riskfolio-Lib==4.0.3
  Using cached Riskfolio-Lib-4.0.3.tar.gz (12.9 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.17.0 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (1.23.5)
Requirement already satisfied: scipy>=1.0.1 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (1.9.3)
Requirement already satisfied: pandas>=1.0.0 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (1.5.2)
Requirement already satisfied: matplotlib>=3.3.0 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (3.6.2)
Requirement already satisfied: cvxpy>=1.0.25 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (1.2.2)
Requirement already satisfied: scikit-learn>=0.22.0 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (1.1.2)
Requirement already satisfied: statsmodels>=0.10.1 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (0.13.5)
Requirement already satisfied: arch>=4.15 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (5.3.1)
Requirement already satisfied: xlsxwriter>=1.3.7 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (3.0.3)
Requirement already satisfied: networkx>=2.5.1 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (2.8.6)
Requirement already satisfied: astropy>=4.3.1 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (5.1)
Requirement already satisfied: pybind11>=2.10.1 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from Riskfolio-Lib==4.0.3) (2.10.1)
Requirement already satisfied: property-cached>=1.6.4 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from arch>=4.15->Riskfolio-Lib==4.0.3) (1.6.4)
Requirement already satisfied: PyYAML>=3.13 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from astropy>=4.3.1->Riskfolio-Lib==4.0.3) (6.0)
Requirement already satisfied: pyerfa>=2.0 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from astropy>=4.3.1->Riskfolio-Lib==4.0.3) (2.0.0.1)
Requirement already satisfied: packaging>=19.0 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from astropy>=4.3.1->Riskfolio-Lib==4.0.3) (21.3)
Requirement already satisfied: osqp>=0.4.1 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from cvxpy>=1.0.25->Riskfolio-Lib==4.0.3) (0.6.2.post5)
Requirement already satisfied: scs>=1.1.6 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from cvxpy>=1.0.25->Riskfolio-Lib==4.0.3) (3.2.0)
Requirement already satisfied: ecos>=2 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from cvxpy>=1.0.25->Riskfolio-Lib==4.0.3) (2.0.10)
Requirement already satisfied: cycler>=0.10 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from matplotlib>=3.3.0->Riskfolio-Lib==4.0.3) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from matplotlib>=3.3.0->Riskfolio-Lib==4.0.3) (9.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from matplotlib>=3.3.0->Riskfolio-Lib==4.0.3) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from matplotlib>=3.3.0->Riskfolio-Lib==4.0.3) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from matplotlib>=3.3.0->Riskfolio-Lib==4.0.3) (4.37.1)
Requirement already satisfied: contourpy>=1.0.1 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from matplotlib>=3.3.0->Riskfolio-Lib==4.0.3) (1.0.5)
Requirement already satisfied: python-dateutil>=2.7 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from matplotlib>=3.3.0->Riskfolio-Lib==4.0.3) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from pandas>=1.0.0->Riskfolio-Lib==4.0.3) (2022.2.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from scikit-learn>=0.22.0->Riskfolio-Lib==4.0.3) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from scikit-learn>=0.22.0->Riskfolio-Lib==4.0.3) (1.1.0)
Requirement already satisfied: patsy>=0.5.2 in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from statsmodels>=0.10.1->Riskfolio-Lib==4.0.3) (0.5.2)
Requirement already satisfied: qdldl in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from osqp>=0.4.1->cvxpy>=1.0.25->Riskfolio-Lib==4.0.3) (0.1.5.post2)
Requirement already satisfied: six in d:\pycharmprojects\riskfolio\venv\lib\site-packages (from patsy>=0.5.2->statsmodels>=0.10.1->Riskfolio-Lib==4.0.3) (1.16.0)
Building wheels for collected packages: Riskfolio-Lib
  Building wheel for Riskfolio-Lib (setup.py): started
  Building wheel for Riskfolio-Lib (setup.py): finished with status 'error'
  Running setup.py clean for Riskfolio-Lib
Failed to build Riskfolio-Lib
Installing collected packages: Riskfolio-Lib
  Attempting uninstall: Riskfolio-Lib
    Found existing installation: Riskfolio-Lib 3.3.0
    Uninstalling Riskfolio-Lib-3.3.0:
      Successfully uninstalled Riskfolio-Lib-3.3.0
  Running setup.py install for Riskfolio-Lib: started
  Running setup.py install for Riskfolio-Lib: finished with status 'error'
  Rolling back uninstall of Riskfolio-Lib
  Moving to d:\pycharmprojects\riskfolio\venv\lib\site-packages\.ds_store
   from C:\Users\Louis\AppData\Local\Temp\pip-uninstall-if8i1s2i\.ds_store
  Moving to d:\pycharmprojects\riskfolio\venv\lib\site-packages\riskfolio\
   from D:\PycharmProjects\Riskfolio\venv\Lib\site-packages\~iskfolio
  Moving to d:\pycharmprojects\riskfolio\venv\lib\site-packages\riskfolio_lib-3.3.0.dist-info\
   from D:\PycharmProjects\Riskfolio\venv\Lib\site-packages\~iskfolio_lib-3.3.0.dist-info

  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [26 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-38
  creating build\lib.win-amd64-cpython-38\riskfolio
  copying riskfolio\__init__.py -> build\lib.win-amd64-cpython-38\riskfolio
  creating build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\AuxFunctions.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\ConstraintsFunctions.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\DBHT.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\GerberStatistic.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\HCPortfolio.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\OwaWeights.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\ParamsEstimation.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\PlotFunctions.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\Portfolio.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\Reports.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\RiskFunctions.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\__init__.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  creating build\lib.win-amd64-cpython-38\riskfolio\external
  copying riskfolio\external\cppfunctions.py -> build\lib.win-amd64-cpython-38\riskfolio\external
  copying riskfolio\external\__init__.py -> build\lib.win-amd64-cpython-38\riskfolio\external
  running build_ext
  building 'riskfolio.external.functions' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Riskfolio-Lib
  error: subprocess-exited-with-error
  
  Running setup.py install for Riskfolio-Lib did not run successfully.
  exit code: 1
  
  [28 lines of output]
  running install
  D:\PycharmProjects\Riskfolio\venv\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-38
  creating build\lib.win-amd64-cpython-38\riskfolio
  copying riskfolio\__init__.py -> build\lib.win-amd64-cpython-38\riskfolio
  creating build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\AuxFunctions.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\ConstraintsFunctions.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\DBHT.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\GerberStatistic.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\HCPortfolio.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\OwaWeights.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\ParamsEstimation.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\PlotFunctions.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\Portfolio.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\Reports.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\RiskFunctions.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  copying riskfolio\src\__init__.py -> build\lib.win-amd64-cpython-38\riskfolio\src
  creating build\lib.win-amd64-cpython-38\riskfolio\external
  copying riskfolio\external\cppfunctions.py -> build\lib.win-amd64-cpython-38\riskfolio\external
  copying riskfolio\external\__init__.py -> build\lib.win-amd64-cpython-38\riskfolio\external
  running build_ext
  building 'riskfolio.external.functions' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.

Riskfolio-Lib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by dcajasn** [comment]
Message is clear "Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools". Did you read riskfolio-lib installation instructions?, You need to install visual studio build tools. Please only raise an issue after read carefully the documentation.
![D8A8BC64-B8CE-4B9D-8211-20DD7B856769](https://user-images.githubusercontent.com/61527316/210241314-79142bc1-0616-4bc6-9223-da5175c96531.jpeg)

**Comment by plajos1** [comment]
Dear Dan, Thank you for your help. It was my mistake. (some weeks ago when you have solved the issue with Tutorial2 with 4.0.2 version I was able to install that and it worked so I was sure the c++ is working, but when I saw, that there is a new version I tried to install it and since then even the 4.0.2  was not usable. Somehow my c++ could be corrupted)
Thanks again.
