### ISSUE TITLE
use matplotlib from bash shell with plt.show()

### ISSUE THREAD

**Issue by limoon20** [dcajasn/Riskfolio-Lib#14]
Hello,
I am following your very interesting and useful code. Everything is fine (e.g. I can see all the calculations outputs in the tables from tutorial 1, and 2), but I cannot see any of your plots. I check your Portfolio.py and you use matplotlib. Would you please tell me how to get the plots?
I do not use ipynb.
Thank you for your time,
LM

**Comment by dcajasn** [comment]
Hi,
The examples are in jupyter notebook to be more friendly for users, however let me tell you that I develop Riskfolio-Lib using Spyder, this means that first I make the examples in Spyder and then I copy the code into the notebooks. In Spyder 4+ in plots window you can see all plots without problems.

**Comment by limoon20** [comment]
Thank you Dcajasn,
but I don't use jupyter, or spyder. 
I just work with commands from bash. that's why I want to plot using matplotlib calling it with "plt.show()". (*)
LM
P.S. (*) example:
import matplotlib.pyplot as plt
N = BL_weights_vector.shape[0]
fig, ax = plt.subplots(figsize=(15, 7))
ax.set_title('
...
...
ax.set_xticklabels(asset_weights.index.values)
plt.xticks(rotation=90, )
plt.legend(numpoints=1, fontsize=11)
plt.show()

**Comment by dcajasn** [comment]
Looking on internet I find this solution https://stackoverflow.com/questions/36269746/matplotlib-plots-arent-shown-when-running-file-from-bash-terminal. You must write plt.show(blocked=True). I hope this information help you because I've never use commands from bash. On the other hand, to learn I think is better that you use Spyder because it helps you to see what is happen when you execute each line of code.

**Comment by limoon20** [comment]
Sorry,
a simpler question.
when you have
import matplotlib.pyplot as plt
you call it:
plt.show()
So, which is the equivalent of this in your format:
import riskfolio.Portfolio as plf    ?
I mean the equivalent of plt.show(), but using your plf?
Thank you,
LM

**Comment by limoon20** [comment]
Thank you,
but I can plot your efficient frontier without any problems by just using plt.show() at the end of the code.
My problem is for the assets allocation-pie plot.
No worries, I'll figure it out.
Thank you for your time,
LM

**Comment by dcajasn** [comment]
> Sorry,
> a simpler question.
> when you have
> import matplotlib.pyplot as plt
> you call it:
> plt.show()
> So, which is the equivalent of this in your format:
> import riskfolio.Portfolio as plf ?
> I mean the equivalent of plt.show(), but using your plf?
> Thank you,
> LM

You can create a matplotlib figure and then use the ax input in the plot. For example:

fig, ax = plt.subplots()
plf.some_chart( ax=ax )
plt.show()

**Comment by limoon20** [comment]
plt.show() works fine, and I can see the pie-plot in tutorial 3.
I must have done something wrong with the other tutorials.
Really, I am done. Thank you for making available this super useful tutorials and codes.
Cordially,
LM

**Comment by limoon20** [comment]
Thank you  very much for your time,

Cordially,

LM


Sent: Friday, April 23, 2021 at 3:26 PM
