### ISSUE TITLE
files not found for Tutorial 6

### ISSUE THREAD

**Issue by xiaoguangzhu** [dcajasn/Riskfolio-Lib#140]
Hello, 

I am new to this library but this is a great library. I couldn't find the two sample files. Could you please shed some lights? 

Thanks!

Tutorial 6: Portfolio Optimization with Custom Parameters

# Load our custom estimates of input parameters
**custom_mu = pd.read_excel('custom_posterior_mu.xlsx', engine='openpyxl', index_col=0).T
custom_cov = pd.read_excel('custom_posterior_cov.xlsx', engine='openpyxl', index_col=0)**

**Comment by dcajasn** [comment]
Hi @xiaoguangzhu 

This is not an issue, look on examples folder.

Best,
Dany

**Comment by xiaoguangzhu** [comment]
this is helpful. Thanks Dany.
