### ISSUE TITLE
Weight constraints

### ISSUE THREAD

**Issue by andreasklippinge** [dcajasn/Riskfolio-Lib#141]
Hey, 

I'm having some problems creating weight constraints for my portfolio and I've tried to look through some examples and guides but cannot wrap my head around it/get it to work. 
Lets say I have a list of tickers as 
``tickers = ['NCC-B.ST','INTRUM.ST','SECU-B.ST','SKA-B.ST','TEL2-B.ST','PEAB-B.ST','ERIC-B.ST','SBB-B.ST','HM-B.ST','AAPL','TSLA','AMZN']``

I want the algoritm to create the optimum portfolio as usual, but I want to invest at least 2% in each ticker. Can anyone link some comprehensive guide on creating the excel-documents and making the code work, or help me with it directly?

Thanks in advance.

**Comment by ActurialCapital** [comment]
Have a look at [this discussion](https://github.com/dcajasn/Riskfolio-Lib/discussions/133), which is still in progress.

**Comment by andreasklippinge** [comment]
Thanks! 
Surely someone has figured out a working code/model and can share it though?

**Comment by dcajasn** [comment]
Hi @ActurialCapital,

This is not an issue. If you want consulting services, see the consulting fee section.

Best,
Dany
