### ISSUE TITLE
Cumulative Return chart from function: PlotFunctions.plot_drawdown 

### ISSUE THREAD

**Issue by xiaoguangzhu** [dcajasn/Riskfolio-Lib#144]
This is a great chart but it looks like the graph doesn't match the underlying calculated data. The inputs and chart are attached. 

Please take a look.

Thanks

For example:
ax = rp.plot_drawdown(pd.DataFrame(cumrtn_8Y), w = w_8Y, alpha=0.05, height=10, width=20, ax=None)

input: w = w_8Y
input: nav = cumrtn_8Y

Run:
index = nav.index.tolist()
a = nav.to_numpy()
a = np.insert(a, 0, 0, axis=0)
a = np.diff(a, axis=0)
a = a @ w.to_numpy()
prices = 1 + np.insert(a, 0, 0, axis=0)
prices = np.cumprod(prices, axis=0)
prices = np.ravel(prices).tolist()
prices2 = 1 + np.array(np.cumsum(a, axis=0))
prices2 = np.ravel(prices2).tolist()
del prices[0]

The cumulative return should be: 1.4184504368548247
but the chart shows more than 1.5

![download](https://user-images.githubusercontent.com/14846012/214954757-c4a93a72-9735-4798-88f7-b171b13409ee.png)
[a_8Y.xlsx](https://github.com/dcajasn/Riskfolio-Lib/files/10513529/a_8Y.xlsx)

**Comment by dcajasn** [comment]
Hi @xiaoguangzhu,

Calculations are fine. If you read chart title said: "uncompounded drawdown".

Best,
Dany

**Comment by xiaoguangzhu** [comment]
Yes, the drawdown is fine. It is the cumulative return that seems off, it should be around 141% but the top chart shows over 150%.
Please take a look.

**Comment by dcajasn** [comment]
Cumulative returns are compounded returns so they comes from prices not prices2 like drawdown.

**Comment by xiaoguangzhu** [comment]
> Cumulative returns are compounded returns so they comes from prices not prices2 like drawdown.

Thanks.
