### ISSUE TITLE
Missing factor used to annualize expected return and expected risks

### ISSUE THREAD

**Issue by uhasan1** [dcajasn/Riskfolio-Lib#15]
https://github.com/dcajasn/Riskfolio-Lib/blob/709af5302998e1629c3cd79552ebc4bdbf2ba34e/riskfolio/Reports.py#L141-L143

Appears as though missing t_factor -- using monthly data, risk contribution per asset generated via Reports is different from plf.plot_risk_con. Believe due to missing t_factor

**Comment by dcajasn** [comment]
Hi @uhasan1 , 

Thanks to find that error. I forget to update that part, I will fix it at night.

**Comment by dcajasn** [comment]
Hi @uhasan1 , I've just fixed the error.
