### ISSUE TITLE
Allowing sht (to allow short ) in the HCPortfolio NCO method

### ISSUE THREAD

**Issue by AnkitAggarwalAlphagrep** [dcajasn/Riskfolio-Lib#157]
In the HCPortfolio.py class when the using the NCO method for the optimization, we don't pass the "sht" (in the _opt_w function) to the Portfolio __init__ method which is by default assumed to be False. Can we expose this variable to be able to pass? 

Also, was there any reason for the not doing that earlier?

Thank

**Comment by dcajasn** [comment]
Hi @AnkitAggarwalAlphagrep, 

I don't plan to add it by the moment. 

Best regards.

**Comment by AnkitAggarwalAlphagrep** [comment]
@dcajasn Can you please tell me will there be any breaking (logic wise) if i enable it?

**Comment by dcajasn** [comment]
It's open source, do what ever you want, but remember that it's your responsability. I don't know what is going to happen if you allow short constraints.
