### ISSUE TITLE
Pandas 2.0

### ISSUE THREAD

**Issue by knickr** [dcajasn/Riskfolio-Lib#160]
Hi there 

Tried to run some of the example scripts with the latest Python 3.11 and Pandas 2.0 and when I ran this example

Tutorial 6: Portfolio Optimization with Custom Parameters

I get this error on cell 4 "2.2 Plotting portfolio composition" 

The error is "DataFrame' object has no attribute 'append' "

which seems to be related to the upgrade to Pandas 2.0 according to this 

https://towardsdatascience.com/fix-attributeerror-dataframe-object-has-no-attribute-append-9bc1557cc929

so you can no longer use the append method in Pandas going forward.  I know I can roll back to older versions of Pandas but it seems like you may need to update the code to remove the append method and replace with concat.

**Comment by dcajasn** [comment]
Hi @knickr,

Since version 1.4 pandas deprecated append function. I'm going to fix that error on next version.

Best regards,
Dany Cajas

**Comment by guanboo-yang** [comment]
Hi, @dcajasn,

May I ask when the next version will be available?

**Comment by dcajasn** [comment]
Hi @guanboo-yang,

I don't know. I'm a little busy now, but maybe between 2 weeks or 1 month.

Best
Dany

**Comment by dcajasn** [comment]
Hi @knickr,

It was fixed on version 4.2.0.

Best,
Dany

**Comment by knickr** [comment]
Great.  Thanks Dany for fixing it so quickly.
