### ISSUE TITLE
[Feature Request] Add Treynor Black Model for Portfolio Optimization Feature

### ISSUE THREAD

**Issue by tys203831** [dcajasn/Riskfolio-Lib#161]
I found this library have quite a lot  portfolio optimization models.

As mentioned in title above, I would like to suggest to add another model called Treynor black model, as below: https://www.investopedia.com/terms/t/treynorblack.asp

**Comment by dcajasn** [comment]
Hi @tys203831,

After read the paper, this model is not suited for Riskfolio-Lib. 

Best,
Dany
