### ISSUE TITLE
Optimization without return streams

### ISSUE THREAD

**Issue by gshen33** [dcajasn/Riskfolio-Lib#162]
Hello Dany,

Is it possible to optimize a portfolio solely based on expected returns and a covariance matrix (mu and cov) but no return stream? I am trying to optimize a portfolio solely based on JP Morgan's Capital Market Assumptions matrix so I don't have any returns to input.

Thank you!

![Screenshot 2023-05-04 111444](https://user-images.githubusercontent.com/130580070/236252015-0bd0bd0d-882d-4489-8108-8a5486b1b250.jpg)

**Comment by dcajasn** [comment]
Hi @gshen33,

This is not an issue, it is a question. For questions see consulting fees section of README.md file.

Best,
Dany
