### ISSUE TITLE
module 'riskfolio.external.cppfunctions' has no attribute 'kurtosis_matrix'

### ISSUE THREAD

**Issue by JeretQ** [dcajasn/Riskfolio-Lib#164]
module 'riskfolio.external.cppfunctions' has no attribute 'kurtosis_matrix'

I have checked ...\Lib\site-packages\riskfolio\external\cppfunctions.py, it hasn't kurtosis_matrix in it.

**Comment by JeretQ** [comment]
install riskfolio with "pip install riskfolio-lib --user"

**Comment by dcajasn** [comment]
Hi @JeretQ 

Please rise an issue when there is a real issue. Raise an issue after install latest version, read documentation and try to solve the problem by yourself.

Best,
Dany
