### ISSUE TITLE
Alpha hardcoded

### ISSUE THREAD

**Issue by uhasan1** [dcajasn/Riskfolio-Lib#17]
https://github.com/dcajasn/Riskfolio-Lib/blob/33979a32885de8a24c09847ca5a20af584ab54d4/riskfolio/Reports.py#L154

Hi - is alpha meant to be hardcoded?

Also consider (if you feel appropriate) doing ax[[1, 2]] instead of ax[[1, 5]] as from a reading perspective seeing visual cum returns followed by uncompounded DD might be more intuitive to readers.

I hope I am not annoying you with these minor QA issues on your code I am raising -- apologies if I am.

**Comment by uhasan1** [comment]
sorry not hardcoded -- deleting issue

**Comment by dcajasn** [comment]
Hi @uhasan1,

I really appreciate that you take your time to find this mistakes in the code, I will fix the mistakes in new version. Now I'm taking some time because I'm coding the hierarchical risk portofolio models (HRP, HERC y NCO) and some related functions.

Best,
Dany
