### ISSUE TITLE
Plotting erros

### ISSUE THREAD

**Issue by gabrielp18** [dcajasn/Riskfolio-Lib#173]
When running "plot_bar", because the new versions of python dataframe.append doesn't work anymore and needs to be replaced for concat, i got the following error:
`---------------------------------------------------------------------------
AttributeError  Traceback (most recent call last)
/2674597346.py) in ?()
----> 1 ax = rp.plot_bar(w,
      2                  title='Portfolio',
      3                  kind="v",
      4                  others=0.05,

riskfolio/src/PlotFunctions.py) in ?(w, title, kind, others, nrow, cpos, cneg, cothers, height, width, ax)
    871         item = pd.DataFrame(["Others", a1, a2]).T
    872         item.columns = ["labels", "abs_values", "values"]
    873         sizes2 = sizes2[sizes2.index <= l2]
    874         sizes2 = sizes2.sort_values(by=["values"], ascending=False)
--> 875         sizes2 = sizes2.append(item)
    876     else:
    877         sizes2 = sizes2.sort_values(by=["values"], ascending=False)
    878 

pandas/core/generic.py) in ?(self, name)
   5985             and name not in self._accessors
   5986             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987         ):
   5988             return self[name]
-> 5989         return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'append'`

**Comment by dcajasn** [comment]
Hi @gabrielp18,

I've just fixed the error, download version 4.4.1.

Best,
Dany
