### ISSUE TITLE
Constraint violation

### ISSUE THREAD

**Issue by gabrielp18** [dcajasn/Riskfolio-Lib#174]
Something is wrong here. 

Using the following constraints:
               'Sign': ['>=','<=', '>=', '<=', '<=', '<=', '<=', '>='],
               'Weight': [0, 0.3, 0.3748, 0.1, 0.2, 0.1, 0.6049, 0.6049]}

Running the following configurations for HERC:
codependence = 'spearman'
rf = 0
covariance = 'hist'
linkage = 'ward'
max_k = 10
leaf_order = True

The sum of weights of the stock is 120%.
Weights: 32.2, 8.82, 0, 20, 0, 1.97, 57,01.

Doesn't make sense at all!!

**Comment by dcajasn** [comment]
Hi @gabrielp18, can you provide a full example to reproduce your error?

**Comment by dcajasn** [comment]
Hi @gabrielp18 ,

Try Riskfolio-Lib 5.0.0.

Best regards,
Dany Cajas
