### ISSUE TITLE
How to fix "The problem doesn't have a solution with actual input parameters"

### ISSUE THREAD

**Issue by BlockWaving** [dcajasn/Riskfolio-Lib#18]
Hi,

Thanks for publishing this great package! And my pleasure to be the first here!
I’m trying to adapt couple of samples to test on a custom alpha estimates, using an industry constraints and MaxRet target, but the optimize consistently generate message saying:

**_The problem doesn't have a solution with actual input parameters_**

Here is the constrains:
 
Disabled | Type           | Set         | Position   | Sign     | Weight | Type Relative | Relative Set | Relative | Factor
FALSE      | All Assets   |               |                 |  <=      | 0.08      |                       |                    |               | 
FALSE      | All Classes | Industry  |                |  <=       | 0.25     |                       |                    |               |  
FALSE      | All Classes | Industry  |                |  >=       | 0.03     |                        |                   |               |  

There are around 250 assets (stocks) and their respective Industries have been mapped, and the asset_classes matrix has been created.

What may have been the reason that the ‘solution’ couldn’t be found? Where should I look at to find the fix?

Thanks,

**Comment by dcajasn** [comment]
Hi @BlockWaving, if you can, send me your code or the part of the code where you have problems to my email. I think that your problem could arise because you are not defining a covariance matrix. Even when you use a MaxRet objective you need to define a covariance matrix and returns matrix.
