### ISSUE TITLE
Can online portfolio problems be solved?

### ISSUE THREAD

**Issue by catgrandpas** [dcajasn/Riskfolio-Lib#180]
Hello, I saw that the examples you gave seem to be single-period decision-making. Can the sequential decision-making problem be solved? For example, online portfolio selection Li B, Hoi S C H. Online portfolio selection: A survey[J]. ACM Computing Surveys (CSUR), 2014, 46(3): 1-36.

**Comment by dcajasn** [comment]
Hi @catgrandpas,

This is not an issue. Please read the documentation and Readme file before raise and issue.

Best,
Dany
