### ISSUE TITLE
Tutorial 18-AttributeError: 'NoneType' object has no attribute 'to_numpy'-- pls. look into

### ISSUE THREAD

**Issue by WalleZJ** [dcajasn/Riskfolio-Lib#183]
![image](https://github.com/dcajasn/Riskfolio-Lib/assets/136595048/6175f030-1128-43a8-a07a-b0fd68b2fc26)
Hi Sir,

I tried this notebook Tutorial 18, both in

_1. local VScode-Python 3.9, and 
2. github Codespace,-Python 3.10__  

this error message happens.

3. And , vectorbt cant not been found with _'pip install vectorbt==0.23.0"_. only 0.24.0 can be choosed from the list.I'm not sure this caused error.
4. I also tried python 3.7, but more stranged things happend(I can't download data from yfinance, and hd5,.pickle can't been open, it seems need more dependencies and cost time).  So, I give up try env python3.7

 could pls. look into this error in turorials, because time is changing.Tutorials is important for 'getting start' to use this excellent Lib. Appreciate your work again.

**Comment by dcajasn** [comment]
Hi @WalleZJ, are you using anaconda or winpython?.

**Comment by WalleZJ** [comment]
Thanks for your so quick response!
Im using Anaconda, not winpython. And, local editor is  VScode. (by the way, **github code space**, this error happen also.Screenshot  in previous comment is from github code space, the same as **Local VScode**

**Comment by dcajasn** [comment]
It seems that you don't have MOSEK installed. You need to install MOSEK and get a free license. Or change the solver used by riskfolio-lib.

**Comment by WalleZJ** [comment]
When I just delete the Parameter MOSEK, the notebook works, as other notebooks did. Beacause I have no knowledge of MOSEK, and  no hint about denpendency of MOSEK, I have not tried that. I will try later , thank you
