### ISSUE TITLE
Positioning vector here 

### ISSUE THREAD

**Issue by johnfelipe** [dcajasn/Riskfolio-Lib#184]
The positioning vector in an investment portfolio refers to the asset allocation or distribution within a portfolio. This vector determines how investments are spread across different asset classes, such as stocks, bonds, real estate, among others. The purpose of this is to diversify risk and optimize returns, based on the investor's objectives, time horizon, and risk tolerance.

For instance, an investor seeking long-term growth with a moderate risk tolerance might have a positioning vector with a higher percentage in stocks and a lower percentage in bonds. Conversely, a more conservative investor, or one needing short-term access to their funds, might have a positioning vector with a larger proportion of bonds and cash.

This vector is not static and can change over time, adjusting to market conditions, changes in the investor's goals, or shifts in their personal financial situation.

How can review that in your app?

**Comment by dcajasn** [comment]
Hi @johnfelipe, this is not an issue. Your question is about a backtesting library and Riskfolio-Lib is a portfolio optimization library.
