### ISSUE TITLE
Examples pages

### ISSUE THREAD

**Issue by mitgeni** [dcajasn/Riskfolio-Lib#185]
Dany, many thanks for this fantastic job, unfortunatey I found that examples pages are not working anymore, please see the picture below

![image](https://github.com/dcajasn/Riskfolio-Lib/assets/130298198/4057f3f7-81b5-4d31-94c6-44e64ccd4361)

**Comment by dcajasn** [comment]
Hi @mitgeni, 

Examples page is working well, try again.

Best,
Dany
