### ISSUE TITLE
Report generation failing

### ISSUE THREAD

**Issue by RamXX** [dcajasn/Riskfolio-Lib#186]
Hi Dany. Fantastic work with Riskfolio-lib!

I'm getting errors with `rp.jupyter_report`, even when running the example. I tried with different Python envs, from 3.9 to 3.11, on both, Linux and MacOS. The error is the same. The error line at the end is:

```
ValueError: 
Normal: $\mu=0.09%$%, $\sigma=0.78%$%
        ^
ParseException: Expected end of text, found '$'  (at char 8), (line:1, col:9)
```

Let me know if you want me to create a gist with the full stack trace. It's pretty long. Thanks!

**Comment by dcajasn** [comment]
Hi @RamXX,

Try Riskfolio-Lib 5.0.0.

Best regards,
Dany Cajas
