### ISSUE TITLE
support Portfolio optimization with factor model？

### ISSUE THREAD

**Issue by quant2008** [dcajasn/Riskfolio-Lib#190]
Hello, Wonder if [Riskfolio-Lib](https://github.com/dcajasn/Riskfolio-Lib) support Portfolio optimization with factor model？like [this](https://docs.mosek.com/portfolio-cookbook/factormodels.html).

**Comment by dcajasn** [comment]
Hi @quant2008,

This is not an issue. Please read documentation and examples section.

Best,
Dany
