### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by TobiasBulla** [dcajasn/Riskfolio-Lib#196]
Hi,

I have been using riskfolio-lib with Python 3.11 without any issues. However, I have recently upgraded to Python 3.12 and when trying to install riskfolio-lib via pip I get the below error message. Hence, I wanted to ask whether there is a timeline for Python 3.12 support?

Collecting riskfolio-lib
  Using cached Riskfolio-Lib-6.0.0.tar.gz (3.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.24.0 in private\base_202402\lib\site-packages (from riskfolio-lib) (1.26.4)
Requirement already satisfied: scipy>=1.10.0 in private\base_202402\lib\site-packages (from riskfolio-lib) (1.11.3)
Requirement already satisfied: pandas>=2.0.0 in private\base_202402\lib\site-packages (from riskfolio-lib) (2.1.4)
Requirement already satisfied: matplotlib>=3.7.0 in private\base_202402\lib\site-packages (from riskfolio-lib) (3.8.0)
Requirement already satisfied: clarabel>=0.6.0 in private\base_202402\lib\site-packages (from riskfolio-lib) (0.7.1)
Requirement already satisfied: cvxpy>=1.4.0 in private\base_202402\lib\site-packages (from riskfolio-lib) (1.4.3)
Requirement already satisfied: scikit-learn>=1.3.0 in private\base_202402\lib\site-packages (from riskfolio-lib) (1.3.0)
Requirement already satisfied: statsmodels>=0.13.5 in private\base_202402\lib\site-packages (from riskfolio-lib) (0.14.0)
Requirement already satisfied: arch>=5.4 in private\base_202402\lib\site-packages (from riskfolio-lib) (7.0.0)
Requirement already satisfied: xlsxwriter>=3.1.2 in private\base_202402\lib\site-packages (from riskfolio-lib) (3.2.0)
Requirement already satisfied: networkx>=3.0 in private\base_202402\lib\site-packages (from riskfolio-lib) (3.1)
Requirement already satisfied: astropy>=5.1 in private\base_202402\lib\site-packages (from riskfolio-lib) (5.3.4)
Requirement already satisfied: pybind11>=2.10.1 in private\base_202402\lib\site-packages (from riskfolio-lib) (2.12.0)
Requirement already satisfied: pyerfa>=2.0 in private\base_202402\lib\site-packages (from astropy>=5.1->riskfolio-lib) (2.0.0)
Requirement already satisfied: PyYAML>=3.13 in private\base_202402\lib\site-packages (from astropy>=5.1->riskfolio-lib) (6.0.1)
Requirement already satisfied: packaging>=19.0 in private\base_202402\lib\site-packages (from astropy>=5.1->riskfolio-lib) (23.2)
Requirement already satisfied: osqp>=0.6.2 in private\base_202402\lib\site-packages (from cvxpy>=1.4.0->riskfolio-lib) (0.6.5)
Requirement already satisfied: ecos>=2 in private\base_202402\lib\site-packages (from cvxpy>=1.4.0->riskfolio-lib) (2.0.13)
Requirement already satisfied: scs>=3.0 in private\base_202402\lib\site-packages (from cvxpy>=1.4.0->riskfolio-lib) (3.2.4.post1)
Requirement already satisfied: contourpy>=1.0.1 in private\base_202402\lib\site-packages (from matplotlib>=3.7.0->riskfolio-lib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in private\base_202402\lib\site-packages (from matplotlib>=3.7.0->riskfolio-lib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in private\base_202402\lib\site-packages (from matplotlib>=3.7.0->riskfolio-lib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in private\base_202402\lib\site-packages (from matplotlib>=3.7.0->riskfolio-lib) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in private\base_202402\lib\site-packages (from matplotlib>=3.7.0->riskfolio-lib) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in private\base_202402\lib\site-packages (from matplotlib>=3.7.0->riskfolio-lib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in private\base_202402\lib\site-packages (from matplotlib>=3.7.0->riskfolio-lib) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in private\base_202402\lib\site-packages (from pandas>=2.0.0->riskfolio-lib) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in private\base_202402\lib\site-packages (from pandas>=2.0.0->riskfolio-lib) (2023.3)
Requirement already satisfied: joblib>=1.1.1 in private\base_202402\lib\site-packages (from scikit-learn>=1.3.0->riskfolio-lib) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in private\base_202402\lib\site-packages (from scikit-learn>=1.3.0->riskfolio-lib) (2.2.0)
Requirement already satisfied: patsy>=0.5.2 in private\base_202402\lib\site-packages (from statsmodels>=0.13.5->riskfolio-lib) (0.5.3)
Requirement already satisfied: qdldl in private\base_202402\lib\site-packages (from osqp>=0.6.2->cvxpy>=1.4.0->riskfolio-lib) (0.1.7.post2)
Requirement already satisfied: six in private\base_202402\lib\site-packages (from patsy>=0.5.2->statsmodels>=0.13.5->riskfolio-lib) (1.16.0)
Building wheels for collected packages: riskfolio-lib
  Building wheel for riskfolio-lib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for riskfolio-lib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\riskfolio
      copying riskfolio\version.py -> build\lib.win-amd64-cpython-312\riskfolio
      copying riskfolio\__init__.py -> build\lib.win-amd64-cpython-312\riskfolio
      creating build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\AuxFunctions.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\ConstraintsFunctions.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\DBHT.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\GerberStatistic.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\HCPortfolio.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\OwaWeights.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\ParamsEstimation.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\PlotFunctions.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\Portfolio.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\Reports.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\RiskFunctions.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      copying riskfolio\src\__init__.py -> build\lib.win-amd64-cpython-312\riskfolio\src
      creating build\lib.win-amd64-cpython-312\riskfolio\external
      copying riskfolio\external\cppfunctions.py -> build\lib.win-amd64-cpython-312\riskfolio\external
      copying riskfolio\external\__init__.py -> build\lib.win-amd64-cpython-312\riskfolio\external
      running build_ext
      building 'riskfolio.external.functions' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for riskfolio-lib
Failed to build riskfolio-lib
ERROR: Could not build wheels for riskfolio-lib, which is required to install pyproject.toml-based projects

**Comment by dcajasn** [comment]
Hi @TobiasBulla, 

Sorry for the delay in response. Riskfolio-Lib supports Python 3.8 or higher, however my GitHub actions only build wheels for until 3.11. I've just updated this error and now there are wheels for Python 3.12 for windows.

Best,
Dany
