### ISSUE TITLE
Possible conceptual error in implementation on HRP (De Prado)

### ISSUE THREAD

**Issue by gioxc88** [dcajasn/Riskfolio-Lib#198]
Hello and thank you for this library 

I was looking at the code and it seems to me that in the implementation of HRP the distance is not properly calculated
If I am not wrong the library only calculates the distance correlation as:

dist = sqrt((1 - corr) / 2)

but in the actual paper this distance is further processed.
In fact De Prado computes the Euclidean distance of any pair of columns and this is the distance actually used in calculating the dendrogram 

it seems like the last step is missing

**Comment by dcajasn** [comment]
Hi @gioxc88.

There is no error. Scipy Linkage function calculate the euclidean distance of distances. Here is an example comparing the results of HRP using several libraries https://financioneroncios.wordpress.com/2021/05/25/hierarchical-risk-parity-hrp-and-hierarchical-equal-risk-contribution-herc-with-python/

PS. Please, before raise an issue check the math and the code. It seems that you only read the source code and formula in HRP paper, but didn't try to reproduce step by step the HRP algorithm and check what each scipy function do. 

Best,
Dany
