### ISSUE TITLE
Problem After Code Update

### ISSUE THREAD

**Issue by sahalaaa** [dcajasn/Riskfolio-Lib#201]
Hi Dani, a few weeks ago I tried your old code on Mean-EVaR Optimization and it seemed to work. But, when i try it today, the code to get the portfolio composition plot seems not working. I checked again and it seems a few things have changed. I already tried to re-install the Riskfolio-Lib but when importing the riskfolio.Portfolio, it cant found the module, so do the riskfolio.PlotFunctions.

**Comment by dcajasn** [comment]
Hi @sahalaaa,

Uninstall and install again, also by the moment Riskfolio is not compatible with matplotlib 3.8 or higher

Best,
Dany
