### ISSUE TITLE
How to add custom index to jupyter_report() cumulative returns plot?

### ISSUE THREAD

**Issue by petric3** [dcajasn/Riskfolio-Lib#204]
I'm using report generator, i.e.
```
ax1 = rp.jupyter_report(returns, w, rm=rm)
plt.show()
```
In the report there's `Historical Compounded Cumulative Returns` plot. How to add a custom index, e.g. S&P 500 to the plot in the report? One can make separate plot with using `ax1`, but it'd make sense to be able to add a custom benchmark index to the cumulative return in the report itself.

**Comment by dcajasn** [comment]
Hi @petric3,

This is not an issue. About your question, you have to add the plot manually. 

Best,
Dany

**Comment by petric3** [comment]
I found the way:
`ax1[1].plot(1+returns["SPY"].cumsum(), color = "black", label = "SPY")`
