### ISSUE TITLE
 NaN Values in Mean Variance Risk Measure for Some Assets in HRP Optimization

### ISSUE THREAD

**Issue by MhmdFasihi** [dcajasn/Riskfolio-Lib#210]
I am currently working on a Hierarchical Risk Parity (HRP) optimization using the riskfolio-lib library and have encountered an issue specifically related to the Mean Variance (MV) risk measure.
Here are the details:
 I have implemented HRP optimization with constraints, and while I am obtaining good results with all other risk measure methods, I consistently receive NaN values for some of my assets when I set MV as the risk measure.

I have attempted to adjust various code dependencies and configurations, but regardless of the changes made, the NaN results persist specifically for the MV risk measure.
The issue seems to be isolated to this risk measure, as other methods function correctly.
![Screenshot 2024-09-26 171239](https://github.com/user-attachments/assets/fa8a4cca-3008-4f18-9887-13d6eb7adf06)

**Comment by dcajasn** [comment]
Hi @MhmdFasihi 

Can you send a reproducible code?

Best,
Dany

**Comment by MhmdFasihi** [comment]
Hi @dcajasn 
thank you for your response 
here is link of my Google Colab code.
https://colab.research.google.com/drive/1SSWCrQ0C2V0O_d2x4jYxlBqNRoASSa6Z?usp=sharing
best,
mhmd

**Comment by MhmdFasihi** [comment]
sorry, could you please have a look to this https://colab.research.google.com/drive/1SSWCrQ0C2V0O_d2x4jYxlBqNRoASSa6Z?usp=sharing one more time, it should work for you.
and ok now I'm working on writing a sample code.

**Comment by dcajasn** [comment]
I told you a simple example, your code have too many things that I don't have time to check, I need a simple example that shows where is the problem.

**Comment by MhmdFasihi** [comment]
When I use your sample code, there is no problem, so I think there is a issue with my functions. again I appreciate for your response and time.

**Comment by MhmdFasihi** [comment]
Here simple code based on your sample tutorial. https://colab.research.google.com/drive/1SSWCrQ0C2V0O_d2x4jYxlBqNRoASSa6Z?usp=sharing

**Comment by MhmdFasihi** [comment]
Hi @dcajasn 
could you please guide me about this issue?
best,
Mhmd

**Comment by dcajasn** [comment]
Hi @MhmdFasihi,

I solved the bug (that happens mainly because your data has too extreme values and too zeros returns), but I will released the fix in next riskfolio-lib version in two or three weeks.

Best regards,
Dany

**Comment by dcajasn** [comment]
Hi @MhmdFasihi,

Download version 6.3.0 to fix the problem.

Best,
Dany
