### ISSUE TITLE
Ask why the RP model does not support MDD ADD

### ISSUE THREAD

**Issue by quanxiang-liu** [dcajasn/Riskfolio-Lib#213]
I'm in check [riskfolio/SRC/Portfolio](https://github.com/dcajasn/Riskfolio-Lib/blob/master/riskfolio/src/Portfolio.py#L3443). Py code found that risk7 SLPM directly below are risk10 CDaR seemed to lack the two risk function（risk 8 MDD & risk9 ADD）, is unable to solve or what made you give them
![image](https://github.com/user-attachments/assets/75089f71-823c-4ec7-b44e-7e82dca408be)

    Thank you and look forward to your reply

**Comment by dcajasn** [comment]
Hi @quanxiang-liu,

This is not an issue. You can make questions in discussion section.

Best,
Dany
