### ISSUE TITLE
UnboundLocalError: local variable 'pvalues' referenced before assignment

### ISSUE THREAD

**Issue by blenderben2** [dcajasn/Riskfolio-Lib#22]
Hi, I am trying out factor models and ran into this error:

> UnboundLocalError: local variable 'pvalues' referenced before assignment

which is coming from this line
https://github.com/dcajasn/Riskfolio-Lib/blob/4087c5de1c1cac374b0581deae1634173989d1c6/riskfolio/ParamsEstimation.py#L204

Probably because for my dataset I didn't run into this condition:
https://github.com/dcajasn/Riskfolio-Lib/blob/4087c5de1c1cac374b0581deae1634173989d1c6/riskfolio/ParamsEstimation.py#L199

maybe an `else` condition could help to handle it.

Also, is it uncommon for this to occur? Is it a big deal? If so, how do I change my data/factors to ensure this doesn't occur?

**Comment by dcajasn** [comment]
Hi, I remember that when I was writing that part I left that code on purpouse because I wanted that an error appears when there is no significant variables among risk factors. Meanwhile I check that part, you should try to add it more risk factors or change the criterion to AIC or BIS.

**Comment by blenderben2** [comment]
will try it out thanks
