### ISSUE TITLE
TypeError: Linkage matrix 'Z' must contain doubles.

### ISSUE THREAD

**Issue by blenderben2** [dcajasn/Riskfolio-Lib#23]
Hi, I am trying out HRP Portfolio, and its unclear from the tutorial which part of the data should be data type `doubles`. 

I tried to convert my df before passing into `HCPortfolio`, but the error still occurs:

```
df = df.astype(np.double)

port = hc.HCPortfolio(returns=df)
```

**Comment by dcajasn** [comment]
Hi, Riskfolio-Lib only takes a returns dataframe as input, never ask for a double type, try with float. I think that the problem is in your data, maybe some nans or str values that makes that the error ocurrs.

**Comment by blenderben2** [comment]
seems like i am not running into this issue for now, will open again if occurs
