### ISSUE TITLE
Tutorial 5, In[12] - "Length mismatch"

### ISSUE THREAD

**Issue by mmmaurice** [dcajasn/Riskfolio-Lib#24]
Hello Dany!

Thanks for your great and comprehensive work.

When running Tutorial 5 without any amendment from my side all goes well until 

**In [12] #Building a loop that estimate optimal portfolios on rebalancing dates**

Error message: The problem doesn't have a solution with actual input parameters.

Value error: Length mismatch: Expected axis has 0 elements, new values have 29 elements.

~\AppData\Roaming\Python\Python38\site-packages\pandas\core\internals\managers.py in set_axis(self, axis, new_labels)
    224 
    225         if new_len != old_len:
--> 226             raise ValueError(
    227                 f"Length mismatch: Expected axis has {old_len} elements, new "
    228                 f"values have {new_len} elements"

index_ is 
[1005,
 1066,
 1129,
 1193,
 1257,
 1318,
 1381,
 1445,
 1509,
 1570,
 1634,
 1698,
 1761,
 1823,
 1886,
 1949,
 2012,
 2073,
 2137,
 2200,
 2263,
 2324,
 2387,
 2451,
 2515,
 2577,
 2640,
 2704,
 2767]

weights, w, models[j], are empty df with shape(0,0).

Can you please help?

Thank you very much in advance!

**Comment by dcajasn** [comment]
Hi @mmmaurice,

When I run the tutorial in my computer I don't have any kind of problem. I think that the problem is that you don't have installed mosek or you don't have a valid mosek license, try to install it or change the line "port.solvers = ['MOSEK']" to  "# port.solvers = ['MOSEK']".

Best,
Dany

**Comment by mmmaurice** [comment]
> Hi @mmmaurice,
> 
> When I run the tutorial in my computer I don't have any kind of problem. I think that the problem is that you don't have installed mosek or you don't have a valid mosek license, try to install it or change the line "port.solvers = ['MOSEK']" to "# port.solvers = ['MOSEK']".
> 
> Best,
> Dany

Thank you so much, Dany - you were absolutely right. I just # the MOSEK.

Wish you a very pleasant day!
Maurice
