### ISSUE TITLE
Smart Sharpe Ratio and Serenity Ratio Objectives

### ISSUE THREAD

**Issue by blenderben2** [dcajasn/Riskfolio-Lib#25]
Here is another objective function which might be of interest to you: [Smart Sharpe Ratio - Part 2](https://www.keyquant.com/Download/GetFile?Filename=%5CPublications%5CKeyQuant_WhitePaper_APT_Part2.pdf), which builds off [Serenity Ratio - Part 1](https://www.keyquant.com/Download/GetFile?Filename=%5CPublications%5CKeyQuant_WhitePaper_APT_Part1.pdf)

**Comment by dcajasn** [comment]
Hi @blenderben2,

After read the pdfs, they don't bring enough information about how to use smart sharpe ratio, serenity ratio and how to optimize them. Also, I think that both models don't guarantee that they have a global optimal solution and also I think that both models can't be expressed as disciplined convex programming problem.
Finally, Riskfolio-lib is a well documented library. All models available in Riskfolio-Lib come from papers that have a proper theoretical background. So please, analyze well the papers before you raise an issue.

Best,
Dany
