### ISSUE TITLE
number of assets constraint 

### ISSUE THREAD

**Issue by sabirjana** [dcajasn/Riskfolio-Lib#26]
Hi, First of all, thank you for this wonderful library. I tried example 26 which is regarding the number of assets constraint and I am facing the following issue.
![image](https://user-images.githubusercontent.com/52304765/124641349-3c291a80-deac-11eb-8f21-42753bae50b2.png)

Appreciate any help. I also tried other MIP solvers based on the table below however faced the same issue.
![image](https://user-images.githubusercontent.com/52304765/124641545-7397c700-deac-11eb-8512-35eb59df3b92.png)

**Comment by rahold** [comment]
Most solvers are not pre-installed. You can find the link to the installation instructions of Mosek in tutorial 17.

**Comment by dcajasn** [comment]
Hi @sabirjana,

As @rahold said in tutorial 17 are the installation instructions of Mosek. But to be more formal, in documentation, in install section are the installation instructions of Mosek https://riskfolio-lib.readthedocs.io/en/latest/install.html.

As an additional comment, I prefer MOSEK solver to avoid any kind of problem with all portfolio models available in Riskfolio-Lib. 

Best, 
Dany

**Comment by sabirjana** [comment]
Hi Dany, Thank you for your quick response. As MOSEK has a license requirement I tried SCIP instead however still faced the issue. I used conda install -c conda-forge scip and then
![image](https://user-images.githubusercontent.com/52304765/124701754-bc7f6800-df0c-11eb-8eb6-cbfffb3f0b1d.png)

**Comment by dcajasn** [comment]
I've never try SCIP solver, but I think that the problem is too complex for the solver. Cardinality constraint with Sharpe objective (return risk ratio) requires fractional mixed integer programming.

**Comment by sabirjana** [comment]
Do you suggest anything open-source solver other than MOSEK?

**Comment by sabirjana** [comment]
Hi Dany, I tried with 'ECOS_BB' solver and it works. Thanks!
