### ISSUE TITLE
Relative turnover limit

### ISSUE THREAD

**Issue by rahold** [dcajasn/Riskfolio-Lib#27]
Hi Dany,

This is a great library and you just added the one thing I was missing: cardinal constraints! 

I have a question about the turnover constraints. The port.turnover parameter reflects the maximum deviation in **absolute** value respect to benchmark weights, right? So with a value of 0.05 this means for instance that an asset with benchmark weight 50% should be between 45% and 55% and an asset with benchmark weight 5% should be between 0% and 10%.
Wouldn't it make more sense to have a relative turnover limit? Would it be possible to add the option for relative turnover limits?

**Comment by dcajasn** [comment]
Hi @rahold,

What do you mean by relative turnover? I understand that you want this constraint: |w/w_0| <= x%. I've never seen that kind of constraint, also I'm not sure if this kind of constraint has utility, for example if original weight is too small, a small variation makes that you need to rebalance your portfolio. On the other hand,  for higher weights, you will need a big variation to rebalance your portfolio. For this reason, I don't see any sense on that kind of constraints.

Best
Dany
