### ISSUE TITLE
Discrete Optimization

### ISSUE THREAD

**Issue by RamonHA** [dcajasn/Riskfolio-Lib#28]
Hi! Hope you are doing very well!

I was searching on the example codes, but I have an issue, does your project have already integrated a function to transform weights from the optimization to discrete weights?

An example: transforming the 10% of participation of "A Random Stock" to 5 (to put an example) Stocks of "A Random Stock", all based on the last price of such stock and the initial investment. Or are those final weights already dependent on the last price of the stock and calculated according to them?

I have seen that when we tried to discretize ideal portfolio weights, different performances can be seen.

I hope I have made myself clear.

Thanks in advance!

**Comment by dcajasn** [comment]
Hi @RamonHA 

To solve your problem you have several options:

1. Find a broker that allows fractional shares. I now that Alpaca and Interactive Brokers allow fractional shares.
2. Use pyportfolioopt to discretize your weights. It has two methods: greedy and based on integer programming (this one takes to much time with many assets).
3. Use the Riskfolio-Lib function AuxFunctions.weights_discretizetion() to discretize your weights. This method consist of sucessive rounding and the excedent is allocated to assets with low prices using sucessive rounding.

I hope this information will help you.

Best,
Dany

**Comment by RamonHA** [comment]
Thank you very much for your prompt response.

I will be checking the different options that you shared.

Greetings.
