### ISSUE TITLE
The problem doesn't have a solution with actual input parameters

### ISSUE THREAD

**Issue by nooooo380** [dcajasn/Riskfolio-Lib#29]
I can not run the following code. How can I fix the problem?

import riskfolio.Portfolio as pf

# Building the portfolio object
port = pf.Portfolio(returns=Y)
# Calculating optimum portfolio

# Load our custom estimates of input parameters
custom_mu = pd.read_excel('custom_posterior_mu.xlsx', engine='openpyxl', index_col=0).T
custom_cov = pd.read_excel('custom_posterior_cov.xlsx', engine='openpyxl', index_col=0)

# Input manually the custom parameters:
port.mu = custom_mu / 100 # Custom mean vector.
port.cov = custom_cov / 100 # Custom covariance matrix.

# Estimate optimal portfolio:

model='Classic' # Could be Classic (historical), BL (Black Litterman) or FM (Factor Model)
rm = 'MV' # Risk measure used, this time will be variance
obj = 'Sharpe' # Objective function, could be MinRisk, MaxRet, Utility or Sharpe
hist = True # Use historical scenarios for risk measures that depend on scenarios
rf = 0 # Risk free rate
l = 0 # Risk aversion factor, only useful when obj is 'Utility'

w = port.optimization(model=model, rm=rm, obj=obj, rf=rf, l=l, hist=hist)

display(w.T)

The problem doesn't have a solution with actual input parameters
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-98d2135a3f1f> in <module>
     24 w = port.optimization(model=model, rm=rm, obj=obj, rf=rf, l=l, hist=hist)
     25 
---> 26 display(w.T)

AttributeError: 'NoneType' object has no attribute 'T'

**Comment by dcajasn** [comment]
I don't know, because I've never had problems with that tutorial. Maybe you are uploading a non positive definite matrix.
