### ISSUE TITLE
Back test tutorials - Transactions costs.

### ISSUE THREAD

**Issue by andrewcztrack** [dcajasn/Riskfolio-Lib#3]
Hi @dcajasn !!

I hope your well.!!
Amazing library, well done, its so excellent!

I was wondering if you could add more back test tutorials, which include slippage and transaction costs.

Also would it be possible to add tear sheet functionality.

Thanks again :).

Kind regards and sincere thanks,
Andrew

**Comment by dcajasn** [comment]
hI @andrewcztrack, 

Thanks for your support, it makes me happy that people around the world appreciate and use my work. About your requests:

1. I'm planning to add more examples, I just added one showing how to use xlwings with riskfolio-lib at the request of a reddit user, so I think maybe this week or next one I will add the examples that you just request.
2. I'm planning to add a tearsheet in the next update of the library. Now I have a draft that has two options: display a tearsheet on a jupyter notebook or download an excel report with a charts and statistics with data and formulas. I hope I will finish this feature in January. I would appreciate, if you have time, that you could send me examples or suggestions of what kind of statistics, charts and indicators you think the tearsheet and excel report must have. You can send me this information here or to my mail.

Best wishes
Dany

**Comment by andrewcztrack** [comment]
Hi @dcajasn !! I hope your well! super excited about the new updates.

I think i jupyter notebook would be good on a personal level, but i know the professional inclination is to use excel.

Over the long term, potentially both could be offered. 

Kind regards and thanks again @dcajasn 

Best,
Andrew

**Comment by dcajasn** [comment]
Hi @andrewcztrack 

I update the tutorial 5, now the example considers slippage and broker commissions.

Best,
Dany

**Comment by andrewcztrack** [comment]
thank you so much! @dcajasn

**Comment by dcajasn** [comment]
Hi @andrewcztrack, I just release the last version of Riskfolio-Lib that includes the reports in Jupyter Notebook and Excel. I also add Entropic Value at Risk Optimization. If you like the new features please share in your social networks.
