### ISSUE TITLE
Run examples/Tutorial 1.ipynb and jupyter notebook is restarted

### ISSUE THREAD

**Issue by mc6666** [dcajasn/Riskfolio-Lib#30]
Hi Dany,

Thanks for your great work. Riskfolio-Lib is really fascinating.

I ran examples/Tutorial 1.ipynb and jupyter notebook was restarted As well as  .py file in vs code.
The notebook crashed at "port.efficient_frontier" in "2.3 Calculate efficient frontier", the error happened without any  information. After tracing, I found it hang at line 2187 of Portfolio.py. 

Can you please help?

Thank you very much in advance!

Michael

**Comment by dcajasn** [comment]
Hi Michael,

For scientific python, I recommend that you should use anaconda or winpython. I've never use vscode, I always use Spyder and Jupyter notebooks. 

Best
Dany

**Comment by mc6666** [comment]
Hi Dany,

Thank you for your recommendation.
I tested Tutorial 1.ipynb under Anaconda and jupyter notebook, the kernel restarted too without any additional error message.
it also hanged at  "port.efficient_frontier" in "2.3 Calculate efficient frontier",

Michael

**Comment by dcajasn** [comment]
Hi Michael,

Maybe your distribution has some installation errors. Try to uninstall Riskfolio-Lib and then reinstall it. 

Best
Dany

**Comment by mc6666** [comment]
Thank you for your help.
I tested on colab and worked well, but not worked in Windows OS with several PCs.

**Comment by dcajasn** [comment]
It's your python distribution. Colab only support old versions of Riskfolio-Lib. New versions works with Python +3.7. I tested all tutorials on windows and mac and works well.

**Comment by mc6666** [comment]
Thanks again.
