### ISSUE TITLE
Predictive measure for portfolio rebalancing

### ISSUE THREAD

**Issue by jmrichardson** [dcajasn/Riskfolio-Lib#32]
Hi,

I am very new to Riskfolio-lib and very impressed!  I was hoping that RFL could implement a ranking strategy using a predictive measure to rebalance the portfolio.  The idea is described [here](https://www.reddit.com/r/algotrading/comments/mtp8b5/beating_the_market_with_the_simple_possible/) and basically involves balancing a portfolio daily based on a prediction value for each equity (probability in my case).  Is this something that could be implemented?  I have looked through the tutorials and documentation but not sure if this is a capability?  Thanks for any guidance!

**Comment by dcajasn** [comment]
Hi @jmrichardson,

Thanks for your support. About your request, what you are asking is to implement a group of trading strategies called Online Portfolio Selection (OLPS). These kind of strategies are closer to algorithmic trading than to portfolio optimization. Riskfolio-Lib is focus on portfolio optimization techniques, so by the moment I don't plan to implement these strategies. There is a toolbox in github for matlab and octave that has implementations of this kind of strategies https://github.com/OLPS/OLPS, also Portfoliolab in paid version has OLPS strategies in Python.

Best,
Dany

**Comment by jmrichardson** [comment]
Hi @dcajasn , Thank you for your quick reply!  I will check out the reference link and will hope that someday you may reconsider.  Thanks again and appreciate your work!
