### ISSUE TITLE
type object 'HCPortfolio' has no attribute 'HCPortfolio'

### ISSUE THREAD

**Issue by msh855** [dcajasn/Riskfolio-Lib#37]
I am not I understand why I get this error:

`type object 'HCPortfolio' has no attribute 'HCPortfolio'`

The code is the same from the examples

```
import riskfolio.HCPortfolio as hc

hc.HCPortfolio

# Building the portfolio object
port = hc.HCPortfolio(returns=Y)

# Estimate optimal portfolio:

model='HRP' # Could be HRP or HERC
correlation = 'pearson' # Correlation matrix used to group assets in clusters
rm = 'MV' # Risk measure used, this time will be variance
rf = 0 # Risk free rate
linkage = 'single' # Linkage method used to build clusters
max_k = 10 # Max number of clusters used in two difference gap statistic, only for HERC model
leaf_order = True # Consider optimal order of leafs in dendrogram

w = port.optimization(model=model,
                      codependence=correlation,
                      rm=rm,
                      rf=rf,
                      linkage=linkage,
                      max_k=max_k,
                      leaf_order=leaf_order)

display(w.T)
```
But I get:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-492394d686e1> in <module>
      1 import riskfolio.HCPortfolio as hc
      2 
----> 3 hc.HCPortfolio
      4 
      5 # Building the portfolio object

AttributeError: type object 'HCPortfolio' has no attribute 'HCPortfolio'

**Comment by dcajasn** [comment]
Check the new documentation, now all objects and functions are called using:
import riskfolio as rp
port = rp.HCPortfolio(returns=Y)

**Comment by msh855** [comment]
Thanks. I will check, I tried and get NaN. my Y is a dataframe with returns. 

![image](https://user-images.githubusercontent.com/26636184/131546193-77b1a6e8-4fa1-4275-903b-2784f3c7590d.png)

**Comment by dcajasn** [comment]
Check your dataframe, all time I see that kind of errors is for errors in dataframe (containts nan or other kind of values)

**Comment by msh855** [comment]
This is my dataframe ( have no NaNs as I have imputed missing values) 

![image](https://user-images.githubusercontent.com/26636184/131547052-8a4d1353-ca93-4d28-a80c-36b99ed81f9f.png)

**Comment by msh855** [comment]
fixed. You can close the issue I think

**Comment by dcajasn** [comment]
I was going to tell you that send me your data and code to see where is the problem but if you fixed it Ok
