### ISSUE TITLE
User specified covariance matrix 

### ISSUE THREAD

**Issue by msh855** [dcajasn/Riskfolio-Lib#39]
Is possible to use a user-specified covariance matrix in the portfolio optimisation, especially with regards to the HRP or HERC? 

I don't see that this possible according to the documentation

**Comment by dcajasn** [comment]
Hi, not by now, when I implement that feature I will release and example.

**Comment by msh855** [comment]
I think is good to have this feature asap because industry people usually work with their own covariance matrix. De Prado's research and article was very influential on this.

**Comment by msh855** [comment]
Up to you. Sound interesting extensions. But my advice is that people would care more about a feature having a user-specified covariance because this is at the heart of all portfolio max problems. In practice, people first try to remove as much of the noise in the covariance matrix as possible by applying their own customised techniques before they use any optimisation routine. 

Anyways, looking forward for these new features then.

**Comment by dcajasn** [comment]
Covariance is only the heart of Markowitz related models. HRP and HERC use naive risk parity and only need covariance when risk measure is variance. For covariance case, Riskfolio-Lib has options to reduce noise, for example we can use shrinkage methods like ledoit-wolf, oas and oracle; also you can use ewma methods to increase the weights of last observations in estimated covariance.

**Comment by msh855** [comment]
Correct. But read De Prado's Asset Management on the covariance matrix. I am only telling you my opinion that between those priorities my sense is that the industry would rather prefer to have the feature with a user-specified covariance matrix, rather than other features you mentioned which most likely you get similar results.

**Comment by dcajasn** [comment]
I know that some people prefer to build their own covariance matrix, in Portfolio object there is that option but not in HCPortfolio object. I will try to add this feature when I implement NCO (something like factors_stats, blacklitterman_stats, blfactors_stats and custom cov) but it's not my priority for now. As Riskfolio-Lib is my hobby, in most cases the features that I add are models that seems interesting to me from the mathematical perspective.

**Comment by dcajasn** [comment]
Hi @msh855, I implement the option to use custom covariance in hierarchical clustering portfolios. Update your Riskfolio-Lib version to the latest to try the new features.
