### ISSUE TITLE
Portfolio Optimization - Vectorbt

### ISSUE THREAD

**Issue by andrewcztrack** [dcajasn/Riskfolio-Lib#4]
Hi @dcajasn !!!

I hope your well and are having a nice December.

I was wondering if it maybe possible to integrate the below library for back testing.

https://github.com/polakowo/vectorbt

It is just easy to generate dashboards.

Kind regards and thanks,
Andrew

**Comment by dcajasn** [comment]
Hi @andrewcztrack 

By the moment I don't have plans to integrate backtesting features to Riskfolio-Lib. There are two reasons for that:

1. The objective of Riskfolio-Lib is to facilitate the use of portfolio optimization models, that are mathematically complex, for everyone. For this reason, I want to finish to add all portfolio optimization models and tools that I have planned before thinking in add backtesting features.

2. I think that there are good backtesting libraries that have the ability to work with percentage weights.

I hope you pass a happy new year.

Best wishes, 
Dany
