### ISSUE TITLE
constraints on HRP do not work 

### ISSUE THREAD

**Issue by msh855** [dcajasn/Riskfolio-Lib#49]
Hi, 

I tried to use HRP with bounds on weights but does not seem to work. 

```
# Building the portfolio object
port = rp.HCPortfolio(returns=ret_under_training, w_max=0.25, w_min=0.03)
w = port.optimization(model='HRP')
w

                                                    weights
Aegon Global Equity Market Neut                    0.636207
Artemis UK Select Fund I Acc                       0.025731
BNY Mellon Investment Funds - N                    0.084947
Baillie Gifford American Fund B                    0.013387
Baillie Gifford European Fund B                    0.015596
Baillie Gifford Global Income G                    0.024059
Baillie Gifford Pacific B Acc                      0.031928
Baillie Gifford Positive Change                    0.026448
Fidelity Funds - Global Technology Fund W-acc-gbp  0.020010
MI Chelverton UK Equity Growth                     0.098183
Vanguard FTSE Developed World e                    0.023504
```

**Comment by dcajasn** [comment]
Hi @msh855,

This is not the way to add constraints on Riskfolio-Lib, the proper way is using the function hrp_constraints. In documentation, there is an example that shows how to add constraints to HRP, check this https://nbviewer.org/github/dcajasn/Riskfolio-Lib/blob/master/examples/Tutorial%2029.ipynb

**Comment by msh855** [comment]
Thanks. 

I think you have a lot of things in your library and after some point gets confusing or complicated how to use it. 

The arguments `w_max`  `w_min`what are doing in `HCPortfolio` then?  I think is a bit confusing.

**Comment by dcajasn** [comment]
I checked the documentation and I will fix that part specifiying that w_max and w_min needs to bee created using hrp_constraints. I tried to be consistent creating the hrp_constraint function because it allow to model several kind of constraints at the same time.
I agree that with more complicated models the use of Riskfolio-Lib gets more confusing, for this reason, I made a lot of examples that explain how to use most models and features.

**Comment by msh855** [comment]
Thanks, will try to see how can adjust in my case. However, the process still looks complicated as I cannot really understand what the `disabled` column does 

In a lot of cases, might suffice for users to put constraints on the weight of stocks ( as in my case). Can you please provide an example of this case? 

In your example is not clear where the constraints refer to. Industry? particular stocks ? sector? you group per sector and impose constraints at a sector level? 

In any case, I will try to check out, but perhaps useful to just use my example above, where my scope was to just have a minimum weight of 3% and a maximum of up to 25% for each stock. As I worked with mutual funds and don't care much for sector or industry level constraints.

**Comment by msh855** [comment]
Hi Dany, 

so, one clarification. 

Do the constraints only work for the `HRP` models? what about the  **'`HERC', 'HERC2'`** ?

I manage to get things done for the HRP, but not for HERC or HERC2.

**Comment by dcajasn** [comment]
Hi @msh855,

The constraints are only available for HRP, in the case of HERC and NCO I didn't find a paper about constraints on both models. I have some ideas to do that but I'm a little busy now to test them. Now I'm working on new convex models that will be included in Riskfolio-Lib based on the first draft of my last working paper. I would like that you give me a feedback of my last working paper, here is the link https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3988927.

Best,
Dany

**Comment by msh855** [comment]
Thanks, Dany will with interest when convenient. In general, is missing a process to help select a portfolio from a range of portfolio methods. 

For the constraints point,  it would be HERC/HERC2 to have the option with some constraints. From my experiments, if you put an asset, such as Gold, that insure against tail risk HERC/HERC2 would allocate almost everything in that asset or be too overweight. Which makes sense, but maybe too much in practice.
