### ISSUE TITLE
AttributeError: module 'typing_extensions' has no attribute 'OrderedDictTypedDict' 

### ISSUE THREAD

**Issue by younggotti** [dcajasn/Riskfolio-Lib#50]
Hi,
The following error occurs when I import the library:

 AttributeError: module 'typing_extensions' has no attribute 'OrderedDictTypedDict' 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\anaconda3\lib\site-packages\astropy\units\_typing.py in <module>
      8 try:  # py 3.9+
----> 9     from typing import Annotated
     10 except (ImportError, ModuleNotFoundError):  # optional dependency

ImportError: cannot import name 'Annotated' from 'typing' (C:\Users\domen\anaconda3\lib\typing.py)

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-9-e2f186e9785c> in <module>
----> 1 import riskfolio as rp
      2 
      3 # Plotting Assets Clusters
      4 
      5 ax = rp.plot_dendrogram(returns=Y,

~\anaconda3\lib\site-packages\riskfolio\__init__.py in <module>
      7 """
      8 
----> 9 from .Portfolio import *
     10 from .HCPortfolio import *
     11 from .PlotFunctions import *

~\anaconda3\lib\site-packages\riskfolio\Portfolio.py in <module>
     13 from scipy.linalg import sqrtm
     14 import riskfolio.RiskFunctions as rk
---> 15 import riskfolio.ParamsEstimation as pe
     16 import riskfolio.AuxFunctions as af
     17 

~\anaconda3\lib\site-packages\riskfolio\ParamsEstimation.py in <module>
     14 from sklearn.decomposition import PCA
     15 from numpy.linalg import inv
---> 16 import riskfolio.AuxFunctions as au
     17 import arch.bootstrap as bs
     18 

~\anaconda3\lib\site-packages\riskfolio\AuxFunctions.py in <module>
     18 import scipy.stats as st
     19 from sklearn.metrics import mutual_info_score
---> 20 from astropy.stats import knuth_bin_width, freedman_bin_width, scott_bin_width
     21 
     22 ###############################################################################

~\anaconda3\lib\site-packages\astropy\stats\__init__.py in <module>
     12 """
     13 
---> 14 from . import funcs
     15 from .funcs import *  # noqa
     16 from . import biweight

~\anaconda3\lib\site-packages\astropy\stats\funcs.py in <module>
     14 import numpy as np
     15 
---> 16 import astropy.units as u
     17 from . import _stats
     18 

~\anaconda3\lib\site-packages\astropy\units\__init__.py in <module>
     38 
     39 from .structured import *
---> 40 from .decorators import *
     41 
     42 del bases

~\anaconda3\lib\site-packages\astropy\units\decorators.py in <module>
     11 import numpy as np
     12 
---> 13 from . import _typing as T
     14 from .core import (Unit, UnitBase, UnitsError,
     15                    add_enabled_equivalencies, dimensionless_unscaled)

~\anaconda3\lib\site-packages\astropy\units\_typing.py in <module>
     16 
     17     else:
---> 18         from typing_extensions import *  # override typing
     19 
     20 HAS_ANNOTATED = Annotated is not NotImplemented

AttributeError: module 'typing_extensions' has no attribute 'OrderedDictTypedDict'

Any help^ Thanks

**Comment by dcajasn** [comment]
Uninstall and reinstall pip install -U Riskfolio-Lib. It seems that is an error in astropy. Install astropy using conda.

**Comment by younggotti** [comment]
I fixed upgrading typing_extensions. Thanks
