### ISSUE TITLE
Runtime error 

### ISSUE THREAD

**Issue by msh855** [dcajasn/Riskfolio-Lib#51]
Hi Dany, 

I am getting this warning: 

```
/Users/opt/anaconda3/envs/Spyder_env/lib/python3.8/site-packages/riskfolio/RiskFunctions.py:356: RuntimeWarning: overflow encountered in exp
  value = np.mean(np.exp(-1 / z * a), axis=0)
```

It was not the case before I did an update to Anacoda.

**Comment by dcajasn** [comment]
Hi @msh855,

It seems an error of numpy's installation. Try to update numpy and scipy.

Best,
Dany
