### ISSUE TITLE
Backtrader can't show sharp ratio

### ISSUE THREAD

**Issue by RoyalBilly** [dcajasn/Riskfolio-Lib#54]
Hi Dany,

When i use Tuorial 5 Multi Assets Algorithmic Trading Backtesting with Backtrader code to test my own data, the result can't show sharp ratio. Could you tell me how to fix this problem?
![image](https://user-images.githubusercontent.com/52813429/147089377-c8d8c61b-8239-4f99-baf9-355355e78e4a.png)

**Comment by dcajasn** [comment]
Hi @RoyalBilly,

This is not a problem of Riskfolio-Lib, it is a problem with backtrader. Check backtrader's documentation to see where is the problem.

Best,
Dany
