### ISSUE TITLE
Maximum Diversification

### ISSUE THREAD

**Issue by cryptocoinserver** [dcajasn/Riskfolio-Lib#55]
Found this interesting paper comparing different optimization techniques.
[https://research-api.cbs.dk/ws/portalfiles/portal/62178444/879726_Master_Thesis_Nima_Daniel_15736.pdf](https://research-api.cbs.dk/ws/portalfiles/portal/62178444/879726_Master_Thesis_Nima_Daniel_15736.pdf)
It mentions maximum diversification portfolios. Which I didn't find in this library. 
Maybe this would be a great addition?

Nevertheless thank you for this great package.

**Comment by dcajasn** [comment]
Hi @cryptocoinserver 

Maximum diversification portfolio is a Sharpe ratio portfolio, where the mean vector is replaced by standard deviation vector. Other users asked me to include that model but I don't plan to include it because it can be easily modeled using custom parameters.

Best,
Dany
