### ISSUE TITLE
how essential is arch?

### ISSUE THREAD

**Issue by microprediction** [dcajasn/Riskfolio-Lib#56]
How essential is arch to have in setup? I ask because it's a bit of a headache on mac silicon.

**Comment by dcajasn** [comment]
Hi @microprediction 

The arch library is only used to build the uncertainty sets for the worst case portfolio models. It uses the bootstrapping functions to find box and eliptical confidence intervals of mean vector and covariance matrix. If you know another library to build bootstrapping samples, please send me the library's link.

Best,
Dany
