### ISSUE TITLE
Custom Estimates for Return

### ISSUE THREAD

**Issue by armarion** [dcajasn/Riskfolio-Lib#57]
I have a simple question. If I want to use custom estimates for returns in an optimization, do these need to be specified as expected annual returns or daily (assuming my historical return series is daily timestep)?

**Comment by dcajasn** [comment]
Hi @armarion 

Riskfolio-Lib doesn't consider the frecuency of returns. The only consideration could be in plots, you have to change the t_factor depending on your data frequency.

Best,
Dany
