### ISSUE TITLE
Relax constraint that weights sum to 1

### ISSUE THREAD

**Issue by armarion** [dcajasn/Riskfolio-Lib#58]
Is there a simple way to specify an optimization such that the sum of weights need not sum to 1? For example, if I want to maximize return given a risk constraint (such as maximum volatility), and if I am ok that the portfolio weights sum to less than 1, is there an easy way to implement this?

Thanks!

**Comment by dcajasn** [comment]
There is an example for leveraged portfolios. Please, you must only raise an issue after check all examples and documentation.
