### ISSUE TITLE
how to include new risk funtion?

### ISSUE THREAD

**Issue by rspadim** [dcajasn/Riskfolio-Lib#59]

**Comment by dcajasn** [comment]
What kind of risk measures?

**Comment by rspadim** [comment]
A risk measure to be used at portfolio optimization, for example, i want to minimize % of days with loss

**Comment by dcajasn** [comment]
Hi @rspadim,

There is no option for custom risk measures. On the other hand, Riskfolio-Lib only support convex risk measures and I don't think that you can minimize the % days of losses because is non-convex.

Best,
Dany

**Comment by rspadim** [comment]
Well, it’s lpm with degree 0 instead of 1 (omega) or 2 (sortino)

**Comment by dcajasn** [comment]
LPM with degree 0 is non convex and non concave. I think that can be modeled using MILP but is too difficult to solve, also I suspect that only can be maximized. In the other hand, norms with degree lower than 1 and higher than 0 are concave, and with degree higher equal than 1 are convex.

**Comment by rspadim** [comment]
Maybe a non optimum solution could be allowed? I think it need other optimizer, don’t remember if supported optimizers have it

**Comment by rspadim** [comment]
I must check, but scipy.optimize have some algos that could be used to nonlinear, non differentiable functions with bounds

**Comment by dcajasn** [comment]
Riskfolio-Lib is mainly focus on convex portfolio models. For this reason I don't plan to include non convex risk measures. On the other hand, scipy optimize are not good for that kind of problems, even commercial solvers like GUROBI or MOSEK have problems to solve MILP problems.

**Comment by rspadim** [comment]
I agree
