### ISSUE TITLE
Custom Objective

### ISSUE THREAD

**Issue by amos-peter** [dcajasn/Riskfolio-Lib#60]
Hi, do you have any tutorial on optimizing based on custom objectives, such maximize a set of scores? Thank you!

**Comment by dcajasn** [comment]
Hi @amos-peter.

I don't have a tutorial about that. Also Riskfolio-Lib doesn't support custom objectives, it only supports the objective functions detailed in documentation.

Best,
Dany

**Comment by amos-peter** [comment]
Hi @dcajasn. Thank you for your update

Best regards,

Amos

**Comment by smjure** [comment]
@dcajasn I'd be also very interested in custom objective function. Is there any plan to implement it? Thank you 🙏

**Comment by dcajasn** [comment]
Hi @smjure,

There is no plan to implement custom objective functions by the moment.

Best,
Dany
