### ISSUE TITLE
Risk_Contribution EVaR

### ISSUE THREAD

**Issue by sirhc78** [dcajasn/Riskfolio-Lib#67]
Hi, 
I got those warnings running Risk_Contribution 'EVaR' .
test = rk.Risk_Contribution(w=weights,cov = covariance,returns = curRet.dropna(axis=0),rm='EVaR',alpha=0.01)
site-packages\riskfolio\RiskFunctions.py:357: RuntimeWarning: divide by zero encountered in log   value = z * (np.log(value) + np.log(1 / alpha))
site-packages\scipy\optimize\slsqp.py:63: RuntimeWarning: invalid value encountered in subtract  jac[i] = (func(*((x0+dx,)+args)) - f0)/epsilon

And it returns a nan array when all input are without nans.
array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan])

Is it a normal behaviour?

Best regards

**Comment by sirhc78** [comment]
Is there any parameters to change if I use monthly returns instead of daily returns ?

**Comment by dcajasn** [comment]
> Hi, I got those warnings running Risk_Contribution 'EVaR' . test = rk.Risk_Contribution(w=weights,cov = covariance,returns = curRet.dropna(axis=0),rm='EVaR',alpha=0.01) site-packages\riskfolio\RiskFunctions.py:357: RuntimeWarning: divide by zero encountered in log value = z * (np.log(value) + np.log(1 / alpha)) site-packages\scipy\optimize\slsqp.py:63: RuntimeWarning: invalid value encountered in subtract jac[i] = (func(*((x0+dx,)+args)) - f0)/epsilon
> 
> And it returns a nan array when all input are without nans. array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
> 
> Is it a normal behaviour?
> 
> Best regards

This is a scipy issue, not a Riskfolio-Lib issue. You must update scipy.

**Comment by dcajasn** [comment]
> Is there any parameters to change if I use monthly returns instead of daily returns ?

You can use returns of the frequency you want. The parameter t_factor is only used for presentation purposes in plot functions.
