### ISSUE TITLE
Speed up the solver()

### ISSUE THREAD

**Issue by lemon234071** [dcajasn/Riskfolio-Lib#70]
Is there any method to make the solve() faster, for example to use  multi cpu or gpu?

**Comment by dcajasn** [comment]
Hi @lemon234071,

It depends on the solver that you choose. To reduce computation time is better to use a commercial solver like GUROBI, CEPLEX or MOSEK. All of them offer academic licenses, but personally I prefer  MOSEK because its academic license is less restrictive and also supports all kind of cones. On the other hand, for linear models GUROBI is a little faster in academic version but has more restrictions in the number of variables and constraints.

Best,
Dany

**Comment by lemon234071** [comment]
> Hi @lemon234071,
> 
> It depends on the solver that you choose. To reduce computation time is better to use a commercial solver like GUROBI, CEPLEX or MOSEK. All of them offer academic licenses, but personally I prefer MOSEK because its academic license is less restrictive and also supports all kind of cones. On the other hand, for linear models GUROBI is a little faster in academic version but has more restrictions in the number of variables and constraints.
> 
> Best, Dany

I found that the rp.Portfolio() has the default self.solvers = ["ECOS", "SCS", "OSQP", "CVXOPT"].
So, all i need to do is change it like self.solvers = ["MOSEK"] ? Will there any hidden danger？

**Comment by dcajasn** [comment]
I use these solvers by default because are open source and are installed by default with CVXPY.
Yes, that's the idea but first you must install MOSEK and get an academic license in its website. If you see Entropic Value at Risk tutorial, I use MOSEK to reduce computation time.

**Comment by lemon234071** [comment]
Thank you first, i just tried MOSEK with just pip install MOSEK . It faster but it return the None solution while other solvers return a weights....

**Comment by dcajasn** [comment]
It's because you need a valid license. In riskfolio-lib install instructions are the links to get an academic license.

**Comment by lemon234071** [comment]
Thank you very much i ll try it.

**Comment by lemon234071** [comment]
It works thank you very much, btw, did your tried the cvxpylayers on GPU? Would it be faster???

**Comment by dcajasn** [comment]
No, I didn't try cvxlayers. I use a Macbook air, so I don't have a GPU to try cvxlayers, but based on the information I read on papers, blogs and forums; commercial solvers like GUROBI, CPLEX, XPRESS and MOSEK are the best.

**Comment by lemon234071** [comment]
Thank you very much！

**Comment by lemon234071** [comment]
Hello there,  me again!  Thank you for your time first!

I still have some problems with the speed:

1, With constraints "upperlng“ and “nea”， my problem should be solved with numerical methods. 
Dose the different objective functions will heavily affect the speed? 
(i mean I saw that optimization of sharpe is realized by minimizing the risk with constraints. I mean do the different forms of the function with constraints will be solved by different methods detected by mosek?).
2, Dose the parameter of Mosek will affect the speed and the performance? (i mean in self.sol_params)

My sincerest thanks！
best wishes!

**Comment by lemon234071** [comment]
Hello there,  me again!  Thank you for your time first!

I still have some problems with the speed:

1, With constraints "upperlng“ and “nea”， my problem should be solved with numerical methods. 
Dose the different objective functions will heavily affect the speed? 
(i mean I saw that optimization of sharpe is realized by minimizing the risk with constraints. I mean do the different forms of the function with constraints will be solved by different methods detected by mosek?).
2, Dose the parameter of Mosek will affect the speed and the performance? (i mean in self.sol_params)

My sincerest thanks！
best wishes!
