### ISSUE TITLE
Risk_Budgeting Approach

### ISSUE THREAD

**Issue by hanlidavid** [dcajasn/Riskfolio-Lib#71]
Greetings from Shanghai, China.
Great job, and thx for sharing this module.
I wonder if this module could be updated to have a "risk_budget" charateristic.
i.e. we have sp500, gold and 10y_bond 3 assets
we put hist ret into the module and we want sp500 to contribute 50% of totol portfolio risk, gold 20%, and 10y_bond 30% along with choices of different risk measures(i.e. downside std). [I couldn't find this method in your posted tutorials]
again thank you for your excellent work, hope everything goes well with you

**Comment by dcajasn** [comment]
Hi @hanlidavid,

Thanks for your support. Just change the vector of risk contribution constraints b.

Best,
Dany
