### ISSUE TITLE
Support for cvxpy.Parameter(). 

### ISSUE THREAD

**Issue by lemon234071** [dcajasn/Riskfolio-Lib#72]
Will Riskfolio support follow way?
(If you need to solve this problem multiple times, but with different data, consider using parameters.)
Like this https://stackoverflow.com/questions/44263875/cvxpy-how-to-efficiently-solve-a-series-of-similar-problems .

**Comment by dcajasn** [comment]
No, because Riskfolio-Lib create a new problem each time you try to solve a portfolio problem.
