### ISSUE TITLE
Typo:  in Portfolio.py

### ISSUE THREAD

**Issue by spramuditha** [dcajasn/Riskfolio-Lib#79]
Just noticed, this should be a break. in Portfolio.py: 3259 
       `risk_names = [
            "MV",
            "MAD",
            "GMD" "MSV",`

Should be an easy fix. 
Thank you for this great work!

**Comment by dcajasn** [comment]
Hi @spramuditha ,

Thanks for discover that error. I fixed the error an update some docs.

Best,
Dany
