### ISSUE TITLE
Problem with dendrogram labels

### ISSUE THREAD

**Issue by VascoBastos** [dcajasn/Riskfolio-Lib#82]
HI, im getting this bug, can you help?
![image](https://user-images.githubusercontent.com/95321254/162451343-fbd48bc5-dc90-481d-a1c7-de861f64177c.png)

**Comment by dcajasn** [comment]
Hi @VascoBastos,

It seems like your dataframe has empty columns, try to see the column names of your dataframe.

Best,
Dany

**Comment by iwouldnote** [comment]
I'm getting the same issue without any empty columns in dataframe, even in tutorial notebooks.
It looks like this bug started with b5a5d73377d027d706737b657c14ab1bd5d04ca1 commit, namely this line: https://github.com/dcajasn/Riskfolio-Lib/blob/eab385b73ee8619386b4a9059c2494a04504661c/riskfolio/PlotFunctions.py#L2420
`codep` shape is equal to number of columns in `returns`, as a result, labels locations are simply equally distributed from 0 to `codep.shape[0]` with default step 1. Commenting out this line in the library source fixes the issue for me.

**Comment by dcajasn** [comment]
Hi @VascoBastos and @iwouldnote,

Sorry for the delay, I was busy with other projects. I fixed the error in version 3.1.1.

Best,
Dany
