### ISSUE TITLE
Tutorial 18: Multi Assets Algorithmic Trading Backtesting with Vectorbt

### ISSUE THREAD

**Issue by REICHIYAN** [dcajasn/Riskfolio-Lib#88]
@dcajasn Hello, I'm afraid this is an elementary question. When I run the code from Tutorial 18 in Google colab, the "weights = np.ravel(w.to_numpy())" part raises "AttributeError: 'NoneType' object has no attribute 'to_ numpy'". I think the weighting is "nan", how should I address this?

**Comment by dcajasn** [comment]
Hi @REICHIYAN 

When that happens is because the problem doesn't have a solution with actual inputs parameters or because the solver used is inadecuate for the problem that you are trying to solve (like use OSQP for EVaR).

Best,
Dany
