### ISSUE TITLE
Issue plotting chart on Google Colab

### ISSUE THREAD

**Issue by andremassaro** [dcajasn/Riskfolio-Lib#92]
Hello!

The "plot_pie()" function in working just fine on Jupyter but, for some reason, is not working on Colab.

Is I run the following code (as in "Tutorial 1: Classic Mean Risk Optimization", for example):

ax = rp.plot_pie(w=w, title='Sharpe Mean Variance', others=0.05, nrow=25, cmap = "tab20",
                 height=6, width=10, ax=None)

It returns me the following errors (image):

![image](https://user-images.githubusercontent.com/12039253/180122003-a711c043-1c2a-4f37-8720-8e72e79cd7f8.png)

Is there any way to deal with this issue and have the chart plotted on colab?

**Comment by dcajasn** [comment]
Hi @andremassaro 

It works without problems.

![image](https://user-images.githubusercontent.com/61527316/180140551-bd678b24-156c-4d90-b5b1-5aaa5edfa6e1.png)

You must install all required packages before running tutorials in colab.

Best,
Dany

**Comment by andremassaro** [comment]
Hello dany, thanks for your reply.

Now it worked. I was already with the libraries, but I think it was an issue with the native matplotlib installation on colab.
