### ISSUE TITLE
Feature Request: Some ideas from PortfolioCharts

### ISSUE THREAD

**Issue by BrandonKMLee** [dcajasn/Riskfolio-Lib#93]
Here are some charts that might be better in Python than in Excel:
1. Equalizer: Visualizing how portfolios are less volatile than individual assets (excluding radical outliers) https://portfoliocharts.com/portfolio/equalizer/
2. Factoring expenses needed per year (may be spending or "fees")
  - https://portfoliocharts.com/portfolio/retirement-spending/
  - https://portfoliocharts.com/portfolio/withdrawal-rates/
3. Start Date Sensitivity: Checks if the portfolios are temporally valid, or merely an adaptation into speculation https://portfoliocharts.com/portfolio/start-date-sensitivity/ https://portfoliocharts.com/portfolio/long-term-returns/ https://portfoliocharts.com/portfolio/target-accuracy/
4. Cumulative Annual Return heatmap based on starting year https://portfoliocharts.com/portfolio/heat-map/

**Comment by dcajasn** [comment]
Hi @BrandonKMLee,

I think that kind of charts are not suitable for riskfolio-lib. They suit better for a backtesting library or an actuarial library.

Best,
Dany
