### ISSUE TITLE
Max Sharpe not working when all custom returns are negative

### ISSUE THREAD

**Issue by nabojyoti** [dcajasn/Riskfolio-Lib#97]
I am implementing 'Max Sharpe' Portfolio Optimization  using custom mu (custom return ) .When all the custom returns are negative that time i am getting some errors as **You must convert self.cov to a positive definite matrix** . This happens only when i try to implement Max Sharpe Portfolio Optimization . How to resolve this issue? Is there a way to use nonconvex optimizier in Riskfolio-Lib ?
![Screenshot from 2022-08-15 19-06-36](https://user-images.githubusercontent.com/53977728/184650512-9712920e-de7e-4d9e-aa36-fc5749c7376c.png)

**Comment by dcajasn** [comment]
Hi @nabojyoti,

Mathematically, you can't optimize a fractional problem when the denominator is negative. In the case of Sharpe ratio, we minimize the inverse of sharpe ratio assuming expected return is positive.

Best,
Dany
