### ISSUE TITLE
Questions about constraint all assets to have a minimum weight

### ISSUE THREAD

**Issue by wytxty** [dcajasn/Riskfolio-Lib#98]
Hi

I'm trying to get the weights for four different assets with a minimum weight constraint for all four assets. To achieve that I build a assets datafrmae with one coulmn 'Assets', and a constriant dataframe with ten columns and fill the 'Sign' , 'Type', 'Weight'. After that I run the code 'A, B = rp.assets_constraints(constraints, asset)', and I get error like 'return resolver.get_dictionary(VariableWithOffset(var, offset) if offset else var)'. 

Thanks for Help!

Best

![test](https://user-images.githubuserc
![1b734e9f8d658eb90150604bf04bda3](https://user-images.githubusercontent.com/94670228/187347471-52186d3b-319c-4340-ac87-18b258bf605e.png)
ontent.com/94670228/187347429-6060a15a-3f43-43f6-823d-71c05924ca61.png)
![image](https://user-images.githubusercontent.com/94670228/187347514-169e6a49-bf57-4d67-a761-9f90bcd2a6f6.png)

**Comment by dcajasn** [comment]
Hi @wytxty,

Replace nan with empty values ''.

Best,
Dany

**Comment by wytxty** [comment]
Hi!

Thx for yr reply.
I tried it and I still get A and B only contain 1 ndarray, and get error "The matrix ainequality must have the same number of columns that assets' number".

![image](https://user-images.githubusercontent.com/94670228/187361864-e01cc58b-06b4-495f-a7b5-5adf6e94a7e9.png)
![image](https://user-images.githubusercontent.com/94670228/187362029-7858ae29-e2c2-4d45-b8a1-077890d706fe.png)

**Comment by wytxty** [comment]
Thx for help! I found the problem, its False not 'False'!
